"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class AddressLocation(object):
    """Implementation of the 'AddressLocation' model.

    The address of the location

    Attributes:
        city (str): City
        country (str): Country
        postal_code (str): Postal code. Validation according to [Universal Postal
            Union addressing
            system](https://www.upu.int/en/activities/addressing/postal-addressing-sys
            tems-in-member-countries.html).
        region (str): Region
        street_address (str): The street address. Validation according to [Universal
            Postal Union addressing
            system](https://www.upu.int/en/activities/addressing/postal-addressing-sys
            tems-in-member-countries.html)
        street_address_2 (str): Additional street address
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "country": "country",
        "street_address": "street_address",
        "city": "city",
        "postal_code": "postal_code",
        "region": "region",
        "street_address_2": "street_address__2",
    }

    _optionals = [
        "city",
        "postal_code",
        "region",
        "street_address_2",
    ]

    def __init__(
        self,
        country=None,
        street_address=None,
        city=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        region=APIHelper.SKIP,
        street_address_2=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AddressLocation instance."""
        # Initialize members of the class
        if city is not APIHelper.SKIP:
            self.city = city
        self.country = country
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if region is not APIHelper.SKIP:
            self.region = region
        self.street_address = street_address
        if street_address_2 is not APIHelper.SKIP:
            self.street_address_2 = street_address_2

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else None
        street_address =\
            dictionary.get("street_address")\
            if dictionary.get("street_address")\
                else None
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if dictionary.get("postal_code")\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else APIHelper.SKIP
        street_address_2 =\
            dictionary.get("street_address__2")\
            if dictionary.get("street_address__2")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(country,
                   street_address,
                   city,
                   postal_code,
                   region,
                   street_address_2,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=self.country
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _street_address=self.street_address
        _street_address_2=(
            self.street_address_2
            if hasattr(self, "street_address_2")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"country={_country!r}, "
            f"postal_code={_postal_code!r}, "
            f"region={_region!r}, "
            f"street_address={_street_address!r}, "
            f"street_address_2={_street_address_2!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=self.country
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _street_address=self.street_address
        _street_address_2=(
            self.street_address_2
            if hasattr(self, "street_address_2")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"country={_country!s}, "
            f"postal_code={_postal_code!s}, "
            f"region={_region!s}, "
            f"street_address={_street_address!s}, "
            f"street_address_2={_street_address_2!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
