"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Address1(object):
    """Implementation of the 'address1' model.

    Attributes:
        attention (str): ‘Attn.’ (if applicable). Only applicable for B2B customers.
        city (str): Customer’s city.
        country (str): Customer’s country. This value overrides the purchase country
            if they are different. Should follow the standard of ISO 3166 alpha-2.
            E.g. GB, US, DE, SE.
        email (str): Customer’s email address.
        family_name (str): Customers family name in UTF-8 encoding. Cannot be only
            numbers, must be more than 1 character. Allowed special characters: -'’.
            More information can be found [in this
            link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-
            data-requirements/#details-needed-per-market)
        given_name (str): Customers given name in UTF-8 encoding. Cannot be only
            numbers, must be more than 1 character. Allowed special characters: -'’.
            More information can be found [in this
            link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-
            data-requirements/#details-needed-per-market)
        organization_name (str): Organization name (if applicable). Only applicable
            for B2B customers.
        phone (str): Phone number. Preferably a mobile phone number.
        postal_code (str): Customer’s postal code. Validation according to [Universal
            Postal Union addressing
            system](https://www.upu.int/en/activities/addressing/postal-addressing-sys
            tems-in-member-countries.html). E.g. 12345, W1G OPW.
        region (str): Customer’s region or state - Mandatory for US and AU market.
            Validations according to ISO 3166-2 format, e.g. US-OH, AU-ACT, etc.
        street_address (str): Customer’s street address. Validation according to
            [Universal Postal Union addressing
            system](https://www.upu.int/en/activities/addressing/postal-addressing-sys
            tems-in-member-countries.html). Regional formatting is required, as
            follows: UK/US/FR: 33 Cavendish Square Rest of EU: De Ruijterkade 7
        street_address_2 (str): Customer’s street address. Second Line.
        title (str): Customer’s Title. Allowed values per country: UK - "Mr", "Ms" DE
            - "Herr", "Frau" AT: "Herr, "Frau" CH: de-CH: "Herr, "Frau" it-CH:
            "Sig.", "Sig.ra" fr-CH: "M", "Mme"  BE: "Dhr.", "Mevr." NL: "Dhr.",
            "Mevr."
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "attention": "attention",
        "city": "city",
        "country": "country",
        "email": "email",
        "family_name": "family_name",
        "given_name": "given_name",
        "organization_name": "organization_name",
        "phone": "phone",
        "postal_code": "postal_code",
        "region": "region",
        "street_address": "street_address",
        "street_address_2": "street_address2",
        "title": "title",
    }

    _optionals = [
        "attention",
        "city",
        "country",
        "email",
        "family_name",
        "given_name",
        "organization_name",
        "phone",
        "postal_code",
        "region",
        "street_address",
        "street_address_2",
        "title",
    ]

    def __init__(
        self,
        attention=APIHelper.SKIP,
        city=APIHelper.SKIP,
        country=APIHelper.SKIP,
        email=APIHelper.SKIP,
        family_name=APIHelper.SKIP,
        given_name=APIHelper.SKIP,
        organization_name=APIHelper.SKIP,
        phone=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        region=APIHelper.SKIP,
        street_address=APIHelper.SKIP,
        street_address_2=APIHelper.SKIP,
        title=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Address1 instance."""
        # Initialize members of the class
        if attention is not APIHelper.SKIP:
            self.attention = attention
        if city is not APIHelper.SKIP:
            self.city = city
        if country is not APIHelper.SKIP:
            self.country = country
        if email is not APIHelper.SKIP:
            self.email = email
        if family_name is not APIHelper.SKIP:
            self.family_name = family_name
        if given_name is not APIHelper.SKIP:
            self.given_name = given_name
        if organization_name is not APIHelper.SKIP:
            self.organization_name = organization_name
        if phone is not APIHelper.SKIP:
            self.phone = phone
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if region is not APIHelper.SKIP:
            self.region = region
        if street_address is not APIHelper.SKIP:
            self.street_address = street_address
        if street_address_2 is not APIHelper.SKIP:
            self.street_address_2 = street_address_2
        if title is not APIHelper.SKIP:
            self.title = title

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        attention =\
            dictionary.get("attention")\
            if dictionary.get("attention")\
                else APIHelper.SKIP
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        family_name =\
            dictionary.get("family_name")\
            if dictionary.get("family_name")\
                else APIHelper.SKIP
        given_name =\
            dictionary.get("given_name")\
            if dictionary.get("given_name")\
                else APIHelper.SKIP
        organization_name =\
            dictionary.get("organization_name")\
            if dictionary.get("organization_name")\
                else APIHelper.SKIP
        phone =\
            dictionary.get("phone")\
            if dictionary.get("phone")\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if dictionary.get("postal_code")\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else APIHelper.SKIP
        street_address =\
            dictionary.get("street_address")\
            if dictionary.get("street_address")\
                else APIHelper.SKIP
        street_address_2 =\
            dictionary.get("street_address2")\
            if dictionary.get("street_address2")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(attention,
                   city,
                   country,
                   email,
                   family_name,
                   given_name,
                   organization_name,
                   phone,
                   postal_code,
                   region,
                   street_address,
                   street_address_2,
                   title,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _attention=(
            self.attention
            if hasattr(self, "attention")
            else None
        )
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _family_name=(
            self.family_name
            if hasattr(self, "family_name")
            else None
        )
        _given_name=(
            self.given_name
            if hasattr(self, "given_name")
            else None
        )
        _organization_name=(
            self.organization_name
            if hasattr(self, "organization_name")
            else None
        )
        _phone=(
            self.phone
            if hasattr(self, "phone")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _street_address=(
            self.street_address
            if hasattr(self, "street_address")
            else None
        )
        _street_address_2=(
            self.street_address_2
            if hasattr(self, "street_address_2")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attention={_attention!r}, "
            f"city={_city!r}, "
            f"country={_country!r}, "
            f"email={_email!r}, "
            f"family_name={_family_name!r}, "
            f"given_name={_given_name!r}, "
            f"organization_name={_organization_name!r}, "
            f"phone={_phone!r}, "
            f"postal_code={_postal_code!r}, "
            f"region={_region!r}, "
            f"street_address={_street_address!r}, "
            f"street_address_2={_street_address_2!r}, "
            f"title={_title!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _attention=(
            self.attention
            if hasattr(self, "attention")
            else None
        )
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _family_name=(
            self.family_name
            if hasattr(self, "family_name")
            else None
        )
        _given_name=(
            self.given_name
            if hasattr(self, "given_name")
            else None
        )
        _organization_name=(
            self.organization_name
            if hasattr(self, "organization_name")
            else None
        )
        _phone=(
            self.phone
            if hasattr(self, "phone")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _street_address=(
            self.street_address
            if hasattr(self, "street_address")
            else None
        )
        _street_address_2=(
            self.street_address_2
            if hasattr(self, "street_address_2")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attention={_attention!s}, "
            f"city={_city!s}, "
            f"country={_country!s}, "
            f"email={_email!s}, "
            f"family_name={_family_name!s}, "
            f"given_name={_given_name!s}, "
            f"organization_name={_organization_name!s}, "
            f"phone={_phone!s}, "
            f"postal_code={_postal_code!s}, "
            f"region={_region!s}, "
            f"street_address={_street_address!s}, "
            f"street_address_2={_street_address_2!s}, "
            f"title={_title!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
