"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.integrator import Integrator
from klarna.models.originator import Originator


class ApplicationJson(object):
    """Implementation of the 'application/json' model.

    Attributes:
        integrator (Integrator): An integrator is the entity that is responsible for
            the integration with Klarna.
        originators (List[Originator]): Array of originators that are responsible for
            the request. If the request is sent through multiple systems before
            reaching the integrator, each system can be represented as an originator.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "integrator": "integrator",
        "originators": "originators",
    }

    _optionals = [
        "originators",
    ]

    def __init__(
        self,
        integrator=None,
        originators=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ApplicationJson instance."""
        # Initialize members of the class
        self.integrator = integrator
        if originators is not APIHelper.SKIP:
            self.originators = originators

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        integrator =\
            Integrator.from_dictionary(
                dictionary.get("integrator"))\
                if dictionary.get("integrator") else None
        originators = None
        if dictionary.get("originators") is not None:
            originators = [
                Originator.from_dictionary(x)
                    for x in dictionary.get("originators")
            ]
        else:
            originators = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(integrator,
                   originators,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _integrator=self.integrator
        _originators=(
            self.originators
            if hasattr(self, "originators")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"integrator={_integrator!r}, "
            f"originators={_originators!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _integrator=self.integrator
        _originators=(
            self.originators
            if hasattr(self, "originators")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"integrator={_integrator!s}, "
            f"originators={_originators!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
