"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class AssetUrls(object):
    """Implementation of the 'asset_urls' model.

    Attributes:
        descriptive (str): URL of the descriptive asset. Using this dynamic asset
            will make sure that any copy update of Klarna will automatically be
            propagated.
        standard (str): URL of the standard asset. Using this dynamic asset will make
            sure that any copy update of Klarna will automatically be propagated.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "descriptive": "descriptive",
        "standard": "standard",
    }

    _optionals = [
        "descriptive",
        "standard",
    ]

    def __init__(
        self,
        descriptive=APIHelper.SKIP,
        standard=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssetUrls instance."""
        # Initialize members of the class
        if descriptive is not APIHelper.SKIP:
            self.descriptive = descriptive
        if standard is not APIHelper.SKIP:
            self.standard = standard

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        descriptive =\
            dictionary.get("descriptive")\
            if dictionary.get("descriptive")\
                else APIHelper.SKIP
        standard =\
            dictionary.get("standard")\
            if dictionary.get("standard")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(descriptive,
                   standard,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _descriptive=(
            self.descriptive
            if hasattr(self, "descriptive")
            else None
        )
        _standard=(
            self.standard
            if hasattr(self, "standard")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"descriptive={_descriptive!r}, "
            f"standard={_standard!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _descriptive=(
            self.descriptive
            if hasattr(self, "descriptive")
            else None
        )
        _standard=(
            self.standard
            if hasattr(self, "standard")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"descriptive={_descriptive!s}, "
            f"standard={_standard!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
