"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Attachment(object):
    """Implementation of the 'Attachment' model.

    Attachment

    Attributes:
        payment_dispute_attachment_id (str): Unique identifier for the payment
            dispute attachment
        description (str): Optional description of the attachment
        mime_type (str): The MIME type of the attachment.
        url (str): The URL to download the attachment.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_dispute_attachment_id": "payment_dispute_attachment_id",
        "description": "description",
        "mime_type": "mime_type",
        "url": "url",
    }

    _optionals = [
        "description",
        "mime_type",
        "url",
    ]

    def __init__(
        self,
        payment_dispute_attachment_id=None,
        description=APIHelper.SKIP,
        mime_type=APIHelper.SKIP,
        url=APIHelper.SKIP):
        """Initialize a Attachment instance."""
        # Initialize members of the class
        self.payment_dispute_attachment_id = payment_dispute_attachment_id
        if description is not APIHelper.SKIP:
            self.description = description
        if mime_type is not APIHelper.SKIP:
            self.mime_type = mime_type
        if url is not APIHelper.SKIP:
            self.url = url

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_dispute_attachment_id =\
            dictionary.get("payment_dispute_attachment_id")\
            if dictionary.get("payment_dispute_attachment_id")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        mime_type =\
            dictionary.get("mime_type")\
            if dictionary.get("mime_type")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(payment_dispute_attachment_id,
                   description,
                   mime_type,
                   url)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.payment_dispute_attachment_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("payment_dispute_attachment_id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _mime_type=(
            self.mime_type
            if hasattr(self, "mime_type")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!r}, "
            f"description={_description!r}, "
            f"mime_type={_mime_type!r}, "
            f"url={_url!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _mime_type=(
            self.mime_type
            if hasattr(self, "mime_type")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!s}, "
            f"description={_description!s}, "
            f"mime_type={_mime_type!s}, "
            f"url={_url!s}, "
            f")"
        )
