"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Attachment1(object):
    """Implementation of the 'attachment1' model.

    Attributes:
        body (str): The content of the extra merchant data should be presented as a
            string inside this property. The body should be an object containing any
            of the keys and sub-objects described below serialized to JSON. More
            information on that object can be found
            [here](https://docs.klarna.com/api/extra-merchant-data).
        content_type (str): The content type of the body. It is usually represented
            as "application/vnd.klarna.internal.emd-v2+json"
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "content_type": "content_type",
    }

    def __init__(
        self,
        body=None,
        content_type=None,
        additional_properties=None):
        """Initialize a Attachment1 instance."""
        # Initialize members of the class
        self.body = body
        self.content_type = content_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else None
        content_type =\
            dictionary.get("content_type")\
            if dictionary.get("content_type")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   content_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=self.body
        _content_type=self.content_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"content_type={_content_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=self.body
        _content_type=self.content_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"content_type={_content_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
