"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class AuthorizedPaymentMethod(object):
    """Implementation of the 'authorized_payment_method' model.

    Attributes:
        number_of_days (int): The model property of type int.
        number_of_installments (int): The model property of type int.
        mtype (Type1): The model property of type Type1.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "number_of_days": "number_of_days",
        "number_of_installments": "number_of_installments",
    }

    _optionals = [
        "number_of_days",
        "number_of_installments",
    ]

    def __init__(
        self,
        mtype=None,
        number_of_days=APIHelper.SKIP,
        number_of_installments=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AuthorizedPaymentMethod instance."""
        # Initialize members of the class
        if number_of_days is not APIHelper.SKIP:
            self.number_of_days = number_of_days
        if number_of_installments is not APIHelper.SKIP:
            self.number_of_installments = number_of_installments
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        number_of_days =\
            dictionary.get("number_of_days")\
            if dictionary.get("number_of_days")\
                else APIHelper.SKIP
        number_of_installments =\
            dictionary.get("number_of_installments")\
            if dictionary.get("number_of_installments")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   number_of_days,
                   number_of_installments,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _number_of_days=(
            self.number_of_days
            if hasattr(self, "number_of_days")
            else None
        )
        _number_of_installments=(
            self.number_of_installments
            if hasattr(self, "number_of_installments")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"number_of_days={_number_of_days!r}, "
            f"number_of_installments={_number_of_installments!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _number_of_days=(
            self.number_of_days
            if hasattr(self, "number_of_days")
            else None
        )
        _number_of_installments=(
            self.number_of_installments
            if hasattr(self, "number_of_installments")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"number_of_days={_number_of_days!s}, "
            f"number_of_installments={_number_of_installments!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
