"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class CancelOrderRequestStatus(object):
    """Implementation of the 'cancel_order_request_status' model.

    Attributes:
        status (Status1): The status of the order cancellation request.
        check_after (datetime): Timestamp for when we expect a decision to be made on
            order cancellation. (ISO 8601)  This field is only populated if status is
            `PENDING`.
        reason_code (ReasonCode): Reason code for why the order cancellation was
            rejected.  This field is only populated if status is `REJECTED`.
        reason_message (str): Human-readable message for why the order cancellation
            was rejected.  This field is only populated if status is `REJECTED`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "check_after": "check_after",
        "reason_code": "reason_code",
        "reason_message": "reason_message",
    }

    _optionals = [
        "check_after",
        "reason_code",
        "reason_message",
    ]

    def __init__(
        self,
        status=None,
        check_after=APIHelper.SKIP,
        reason_code=APIHelper.SKIP,
        reason_message=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CancelOrderRequestStatus instance."""
        # Initialize members of the class
        self.status = status
        if check_after is not APIHelper.SKIP:
            self.check_after =\
                 APIHelper.apply_datetime_converter(
                check_after, APIHelper.RFC3339DateTime)\
                 if check_after else None
        if reason_code is not APIHelper.SKIP:
            self.reason_code = reason_code
        if reason_message is not APIHelper.SKIP:
            self.reason_message = reason_message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        check_after = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("check_after")).datetime\
            if dictionary.get("check_after") else APIHelper.SKIP
        reason_code =\
            dictionary.get("reason_code")\
            if dictionary.get("reason_code")\
                else APIHelper.SKIP
        reason_message =\
            dictionary.get("reason_message")\
            if dictionary.get("reason_message")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   check_after,
                   reason_code,
                   reason_message,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        _check_after=(
            self.check_after
            if hasattr(self, "check_after")
            else None
        )
        _reason_code=(
            self.reason_code
            if hasattr(self, "reason_code")
            else None
        )
        _reason_message=(
            self.reason_message
            if hasattr(self, "reason_message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"check_after={_check_after!r}, "
            f"reason_code={_reason_code!r}, "
            f"reason_message={_reason_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _check_after=(
            self.check_after
            if hasattr(self, "check_after")
            else None
        )
        _reason_code=(
            self.reason_code
            if hasattr(self, "reason_code")
            else None
        )
        _reason_message=(
            self.reason_message
            if hasattr(self, "reason_message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"check_after={_check_after!s}, "
            f"reason_code={_reason_code!s}, "
            f"reason_message={_reason_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
