"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.address import Address
from klarna.models.order_line import OrderLine
from klarna.models.shipping_info import ShippingInfo


class Capture(object):
    """Implementation of the 'Capture' model.

    Attributes:
        billing_address (Address): Shipping address for the capture.
        capture_id (str): The capture id. Generated when the capture is created.
        captured_amount (int): The captured amount in minor units.
        captured_at (datetime): The time of the capture. Specified in ISO 8601.
        description (str): Description of the capture shown to the customer.
        klarna_reference (str): Customer friendly reference id, used as a reference
            when communicating with the customer.
        order_lines (List[OrderLine]): List of order lines for the capture shown to
            the customer.
        reference (str): Internal reference to the capture which will be included in
            the settlement files. Max length is 255 characters.
        refunded_amount (int): Refunded amount for this capture in minor units.
        shipping_address (Address): Shipping address for the capture.
        shipping_info (List[ShippingInfo]): Shipping information for this capture.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "billing_address": "billing_address",
        "capture_id": "capture_id",
        "captured_amount": "captured_amount",
        "captured_at": "captured_at",
        "description": "description",
        "klarna_reference": "klarna_reference",
        "order_lines": "order_lines",
        "reference": "reference",
        "refunded_amount": "refunded_amount",
        "shipping_address": "shipping_address",
        "shipping_info": "shipping_info",
    }

    _optionals = [
        "billing_address",
        "capture_id",
        "captured_amount",
        "captured_at",
        "description",
        "klarna_reference",
        "order_lines",
        "reference",
        "refunded_amount",
        "shipping_address",
        "shipping_info",
    ]

    def __init__(
        self,
        billing_address=APIHelper.SKIP,
        capture_id=APIHelper.SKIP,
        captured_amount=APIHelper.SKIP,
        captured_at=APIHelper.SKIP,
        description=APIHelper.SKIP,
        klarna_reference=APIHelper.SKIP,
        order_lines=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        refunded_amount=APIHelper.SKIP,
        shipping_address=APIHelper.SKIP,
        shipping_info=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Capture instance."""
        # Initialize members of the class
        if billing_address is not APIHelper.SKIP:
            self.billing_address = billing_address
        if capture_id is not APIHelper.SKIP:
            self.capture_id = capture_id
        if captured_amount is not APIHelper.SKIP:
            self.captured_amount = captured_amount
        if captured_at is not APIHelper.SKIP:
            self.captured_at =\
                 APIHelper.apply_datetime_converter(
                captured_at, APIHelper.RFC3339DateTime)\
                 if captured_at else None
        if description is not APIHelper.SKIP:
            self.description = description
        if klarna_reference is not APIHelper.SKIP:
            self.klarna_reference = klarna_reference
        if order_lines is not APIHelper.SKIP:
            self.order_lines = order_lines
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if refunded_amount is not APIHelper.SKIP:
            self.refunded_amount = refunded_amount
        if shipping_address is not APIHelper.SKIP:
            self.shipping_address = shipping_address
        if shipping_info is not APIHelper.SKIP:
            self.shipping_info = shipping_info

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        billing_address =\
            Address.from_dictionary(
                dictionary.get("billing_address"))\
                if "billing_address" in dictionary.keys()\
                else APIHelper.SKIP
        capture_id =\
            dictionary.get("capture_id")\
            if dictionary.get("capture_id")\
                else APIHelper.SKIP
        captured_amount =\
            dictionary.get("captured_amount")\
            if dictionary.get("captured_amount")\
                else APIHelper.SKIP
        captured_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("captured_at")).datetime\
            if dictionary.get("captured_at") else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        klarna_reference =\
            dictionary.get("klarna_reference")\
            if dictionary.get("klarna_reference")\
                else APIHelper.SKIP
        order_lines = None
        if dictionary.get("order_lines") is not None:
            order_lines = [
                OrderLine.from_dictionary(x)
                    for x in dictionary.get("order_lines")
            ]
        else:
            order_lines = APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        refunded_amount =\
            dictionary.get("refunded_amount")\
            if dictionary.get("refunded_amount")\
                else APIHelper.SKIP
        shipping_address =\
            Address.from_dictionary(
                dictionary.get("shipping_address"))\
                if "shipping_address" in dictionary.keys()\
                else APIHelper.SKIP
        shipping_info = None
        if dictionary.get("shipping_info") is not None:
            shipping_info = [
                ShippingInfo.from_dictionary(x)
                    for x in dictionary.get("shipping_info")
            ]
        else:
            shipping_info = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(billing_address,
                   capture_id,
                   captured_amount,
                   captured_at,
                   description,
                   klarna_reference,
                   order_lines,
                   reference,
                   refunded_amount,
                   shipping_address,
                   shipping_info,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _capture_id=(
            self.capture_id
            if hasattr(self, "capture_id")
            else None
        )
        _captured_amount=(
            self.captured_amount
            if hasattr(self, "captured_amount")
            else None
        )
        _captured_at=(
            self.captured_at
            if hasattr(self, "captured_at")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _klarna_reference=(
            self.klarna_reference
            if hasattr(self, "klarna_reference")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _refunded_amount=(
            self.refunded_amount
            if hasattr(self, "refunded_amount")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _shipping_info=(
            self.shipping_info
            if hasattr(self, "shipping_info")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"billing_address={_billing_address!r}, "
            f"capture_id={_capture_id!r}, "
            f"captured_amount={_captured_amount!r}, "
            f"captured_at={_captured_at!r}, "
            f"description={_description!r}, "
            f"klarna_reference={_klarna_reference!r}, "
            f"order_lines={_order_lines!r}, "
            f"reference={_reference!r}, "
            f"refunded_amount={_refunded_amount!r}, "
            f"shipping_address={_shipping_address!r}, "
            f"shipping_info={_shipping_info!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _capture_id=(
            self.capture_id
            if hasattr(self, "capture_id")
            else None
        )
        _captured_amount=(
            self.captured_amount
            if hasattr(self, "captured_amount")
            else None
        )
        _captured_at=(
            self.captured_at
            if hasattr(self, "captured_at")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _klarna_reference=(
            self.klarna_reference
            if hasattr(self, "klarna_reference")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _refunded_amount=(
            self.refunded_amount
            if hasattr(self, "refunded_amount")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _shipping_info=(
            self.shipping_info
            if hasattr(self, "shipping_info")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"billing_address={_billing_address!s}, "
            f"capture_id={_capture_id!s}, "
            f"captured_amount={_captured_amount!s}, "
            f"captured_at={_captured_at!s}, "
            f"description={_description!s}, "
            f"klarna_reference={_klarna_reference!s}, "
            f"order_lines={_order_lines!s}, "
            f"reference={_reference!s}, "
            f"refunded_amount={_refunded_amount!s}, "
            f"shipping_address={_shipping_address!s}, "
            f"shipping_info={_shipping_info!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
