"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.order_line import OrderLine
from klarna.models.shipping_info import ShippingInfo


class CaptureObject(object):
    """Implementation of the 'CaptureObject' model.

    Capture request data

    Attributes:
        captured_amount (int): The captured amount in minor units.
        description (str): Description of the capture shown to the customer. Maximum
            255 characters.
        order_lines (List[OrderLine]): Order lines for this capture. Maximum 1000
            items.
        reference (str): Internal reference to the capture. This will be included in
            the settlement files. Max length is 255 characters.
        shipping_delay (int): Delay before the order will be shipped. Use for
            improving the customer experience regarding payments. This field is
            currently not returned when reading the order. Minimum: 0. Please note:
            to be able to submit values larger than 0, this has to be enabled in your
            merchant account. Please contact Klarna for further information.
        shipping_info (List[ShippingInfo]): Shipping information for this capture.
            Maximum 500 items.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "captured_amount": "captured_amount",
        "description": "description",
        "order_lines": "order_lines",
        "reference": "reference",
        "shipping_delay": "shipping_delay",
        "shipping_info": "shipping_info",
    }

    _optionals = [
        "description",
        "order_lines",
        "reference",
        "shipping_delay",
        "shipping_info",
    ]

    def __init__(
        self,
        captured_amount=None,
        description=APIHelper.SKIP,
        order_lines=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        shipping_delay=APIHelper.SKIP,
        shipping_info=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CaptureObject instance."""
        # Initialize members of the class
        self.captured_amount = captured_amount
        if description is not APIHelper.SKIP:
            self.description = description
        if order_lines is not APIHelper.SKIP:
            self.order_lines = order_lines
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if shipping_delay is not APIHelper.SKIP:
            self.shipping_delay = shipping_delay
        if shipping_info is not APIHelper.SKIP:
            self.shipping_info = shipping_info

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        captured_amount =\
            dictionary.get("captured_amount")\
            if dictionary.get("captured_amount")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        order_lines = None
        if dictionary.get("order_lines") is not None:
            order_lines = [
                OrderLine.from_dictionary(x)
                    for x in dictionary.get("order_lines")
            ]
        else:
            order_lines = APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        shipping_delay =\
            dictionary.get("shipping_delay")\
            if dictionary.get("shipping_delay")\
                else APIHelper.SKIP
        shipping_info = None
        if dictionary.get("shipping_info") is not None:
            shipping_info = [
                ShippingInfo.from_dictionary(x)
                    for x in dictionary.get("shipping_info")
            ]
        else:
            shipping_info = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(captured_amount,
                   description,
                   order_lines,
                   reference,
                   shipping_delay,
                   shipping_info,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _captured_amount=self.captured_amount
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _shipping_delay=(
            self.shipping_delay
            if hasattr(self, "shipping_delay")
            else None
        )
        _shipping_info=(
            self.shipping_info
            if hasattr(self, "shipping_info")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"captured_amount={_captured_amount!r}, "
            f"description={_description!r}, "
            f"order_lines={_order_lines!r}, "
            f"reference={_reference!r}, "
            f"shipping_delay={_shipping_delay!r}, "
            f"shipping_info={_shipping_info!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _captured_amount=self.captured_amount
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _shipping_delay=(
            self.shipping_delay
            if hasattr(self, "shipping_delay")
            else None
        )
        _shipping_info=(
            self.shipping_info
            if hasattr(self, "shipping_info")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"captured_amount={_captured_amount!s}, "
            f"description={_description!s}, "
            f"order_lines={_order_lines!s}, "
            f"reference={_reference!s}, "
            f"shipping_delay={_shipping_delay!s}, "
            f"shipping_info={_shipping_info!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
