"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class CustomerRead(object):
    """Implementation of the 'customer_read' model.

    Attributes:
        date_of_birth (str): Customer’s date of birth. The format is ‘yyyy-mm-dd’
        gender (str): Customer’s gender - ‘male’ or ‘female’
        organization_entity_type (OrganizationEntityType): Organization entity type.
            Only applicable for B2B customers.
        organization_registration_id (str): Organization registration id. Only
            applicable for B2B customers.
        title (str): Customer’s Title. Allowed values per country: UK - "Mr", "Ms" DE
            - "Herr", "Frau" AT: "Herr, "Frau" CH: de-CH: "Herr, "Frau" it-CH:
            "Sig.", "Sig.ra" fr-CH: "M", "Mme"  BE: "Dhr.", "Mevr." NL: "Dhr.",
            "Mevr."
        mtype (str): Type of customer in the session. If nothing is added, a B2C
            session will be the default. If it is a b2b-session, you should enter
            organization to trigger a B2B session.
        vat_id (str): VAT ID. Only applicable for B2B customers.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date_of_birth": "date_of_birth",
        "gender": "gender",
        "organization_entity_type": "organization_entity_type",
        "organization_registration_id": "organization_registration_id",
        "title": "title",
        "mtype": "type",
        "vat_id": "vat_id",
    }

    _optionals = [
        "date_of_birth",
        "gender",
        "organization_entity_type",
        "organization_registration_id",
        "title",
        "mtype",
        "vat_id",
    ]

    def __init__(
        self,
        date_of_birth=APIHelper.SKIP,
        gender=APIHelper.SKIP,
        organization_entity_type=APIHelper.SKIP,
        organization_registration_id=APIHelper.SKIP,
        title=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        vat_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CustomerRead instance."""
        # Initialize members of the class
        if date_of_birth is not APIHelper.SKIP:
            self.date_of_birth = date_of_birth
        if gender is not APIHelper.SKIP:
            self.gender = gender
        if organization_entity_type is not APIHelper.SKIP:
            self.organization_entity_type = organization_entity_type
        if organization_registration_id is not APIHelper.SKIP:
            self.organization_registration_id = organization_registration_id
        if title is not APIHelper.SKIP:
            self.title = title
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if vat_id is not APIHelper.SKIP:
            self.vat_id = vat_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        date_of_birth =\
            dictionary.get("date_of_birth")\
            if dictionary.get("date_of_birth")\
                else APIHelper.SKIP
        gender =\
            dictionary.get("gender")\
            if dictionary.get("gender")\
                else APIHelper.SKIP
        organization_entity_type =\
            dictionary.get("organization_entity_type")\
            if dictionary.get("organization_entity_type")\
                else APIHelper.SKIP
        organization_registration_id =\
            dictionary.get("organization_registration_id")\
            if dictionary.get("organization_registration_id")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        vat_id =\
            dictionary.get("vat_id")\
            if dictionary.get("vat_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(date_of_birth,
                   gender,
                   organization_entity_type,
                   organization_registration_id,
                   title,
                   mtype,
                   vat_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _gender=(
            self.gender
            if hasattr(self, "gender")
            else None
        )
        _organization_entity_type=(
            self.organization_entity_type
            if hasattr(self, "organization_entity_type")
            else None
        )
        _organization_registration_id=(
            self.organization_registration_id
            if hasattr(self, "organization_registration_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _vat_id=(
            self.vat_id
            if hasattr(self, "vat_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date_of_birth={_date_of_birth!r}, "
            f"gender={_gender!r}, "
            f"organization_entity_type={_organization_entity_type!r}, "
            f"organization_registration_id={_organization_registration_id!r}, "
            f"title={_title!r}, "
            f"mtype={_mtype!r}, "
            f"vat_id={_vat_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _gender=(
            self.gender
            if hasattr(self, "gender")
            else None
        )
        _organization_entity_type=(
            self.organization_entity_type
            if hasattr(self, "organization_entity_type")
            else None
        )
        _organization_registration_id=(
            self.organization_registration_id
            if hasattr(self, "organization_registration_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _vat_id=(
            self.vat_id
            if hasattr(self, "vat_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date_of_birth={_date_of_birth!s}, "
            f"gender={_gender!s}, "
            f"organization_entity_type={_organization_entity_type!s}, "
            f"organization_registration_id={_organization_registration_id!s}, "
            f"title={_title!s}, "
            f"mtype={_mtype!s}, "
            f"vat_id={_vat_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
