"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from klarna.api_helper import APIHelper


class Customer(object):
    """Implementation of the 'customer' model.

    Information about the customer placing the order.

    Attributes:
        date_of_birth (date): The customer date of birth. ISO 8601.
        national_identification_number (str): The customer national identification
            number
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date_of_birth": "date_of_birth",
        "national_identification_number": "national_identification_number",
    }

    _optionals = [
        "date_of_birth",
        "national_identification_number",
    ]

    def __init__(
        self,
        date_of_birth=APIHelper.SKIP,
        national_identification_number=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Customer instance."""
        # Initialize members of the class
        if date_of_birth is not APIHelper.SKIP:
            self.date_of_birth = date_of_birth
        if national_identification_number is not APIHelper.SKIP:
            self.national_identification_number = national_identification_number

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        date_of_birth = dateutil.parser.parse(
            dictionary.get("date_of_birth")).date()\
            if dictionary.get("date_of_birth") else APIHelper.SKIP
        national_identification_number =\
            dictionary.get("national_identification_number")\
            if dictionary.get("national_identification_number")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(date_of_birth,
                   national_identification_number,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _national_identification_number=(
            self.national_identification_number
            if hasattr(self, "national_identification_number")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date_of_birth={_date_of_birth!r}, "
            f"national_identification_number={_national_identification_number!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _national_identification_number=(
            self.national_identification_number
            if hasattr(self, "national_identification_number")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date_of_birth={_date_of_birth!s}, "
            f"national_identification_number={_national_identification_number!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
