"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.pagination_response import (
    PaginationResponse,
)


class DisputesList(object):
    """Implementation of the 'DisputesList' model.

    Attributes:
        disputes (List[PaymentDisputeBodyDisputeInitiated |
            PaymentDisputeBodyRepresentment | PaymentDisputeBodyPreArbitration |
            PaymentDisputeBodyArbitration | PaymentDisputeBodyClosed]): The model
            property of type List[PaymentDisputeBodyDisputeInitiated |
            PaymentDisputeBodyRepresentment | PaymentDisputeBodyPreArbitration |
            PaymentDisputeBodyArbitration | PaymentDisputeBodyClosed].
        pagination (PaginationResponse): A paginated response will return this object
            with information about the size and links to any next and previous pages.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "disputes": "disputes",
        "pagination": "pagination",
    }

    def __init__(
        self,
        disputes=None,
        pagination=None):
        """Initialize a DisputesList instance."""
        # Initialize members of the class
        self.disputes = disputes
        self.pagination = pagination

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from klarna.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        disputes = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PaymentDisputeBody2"),
            dictionary.get("disputes"),
            False)\
            if dictionary.get("disputes") is not None\
            else None
        pagination =\
            PaginationResponse.from_dictionary(
                dictionary.get("pagination"))\
                if dictionary.get("pagination") else None

        # Return an object of this model
        return cls(disputes,
                   pagination)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from klarna.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("PaymentDisputeBody2")
                .validate(dictionary.disputes).is_valid) \
                and APIHelper.is_valid_type(
                    value=dictionary.pagination,
                    type_callable=lambda value:
                        PaginationResponse.validate(value),
                    is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("PaymentDisputeBody2")
            .validate(dictionary.get("disputes")).is_valid) \
            and APIHelper.is_valid_type(
                value=dictionary.get("pagination"),
                type_callable=lambda value:
                    PaginationResponse.validate(value),
                is_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _disputes=self.disputes
        _pagination=self.pagination
        return (
            f"{self.__class__.__name__}("
            f"disputes={_disputes!r}, "
            f"pagination={_pagination!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _disputes=self.disputes
        _pagination=self.pagination
        return (
            f"{self.__class__.__name__}("
            f"disputes={_disputes!s}, "
            f"pagination={_pagination!s}, "
            f")"
        )
