"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.option_dto import OptionDto


class ExtendDueDateOptions(object):
    """Implementation of the 'ExtendDueDateOptions' model.

    Attributes:
        currency (str): The currency for the fees. Specified in ISO 4217 format.
        options (List[OptionDto]): The available options and corresponding fees for
            extending the due date
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "currency": "currency",
        "options": "options",
    }

    _optionals = [
        "currency",
        "options",
    ]

    def __init__(
        self,
        currency=APIHelper.SKIP,
        options=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ExtendDueDateOptions instance."""
        # Initialize members of the class
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if options is not APIHelper.SKIP:
            self.options = options

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        options = None
        if dictionary.get("options") is not None:
            options = [
                OptionDto.from_dictionary(x)
                    for x in dictionary.get("options")
            ]
        else:
            options = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(currency,
                   options,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"currency={_currency!r}, "
            f"options={_options!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"currency={_currency!s}, "
            f"options={_options!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
