"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class InitialPaymentMethodDto(object):
    """Implementation of the 'InitialPaymentMethodDto' model.

    Initial payment method for this order

    Attributes:
        description (str): The description of the initial payment method.
        number_of_installments (int): The number of installments (if applicable).
        mtype (str): The type of the initial payment method. One of ACCOUNT,
            ALTERNATIVE_PAYMENT_METHOD, BANK_TRANSFER, CARD, DEFERRED_INTEREST,
            DIRECT_DEBIT, FIXED_AMOUNT_BY_CARD, FIXED_AMOUNT, FIXED_SUM_CREDIT,
            INVOICE_BUSINESS, INVOICE, MOBILEPAY, PAY_BY_CARD, PAY_IN_X,
            PAY_LATER_BY_CARD, PAY_LATER_IN_PARTS, SWISH, OTHER
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "description": "description",
        "number_of_installments": "number_of_installments",
        "mtype": "type",
    }

    _optionals = [
        "description",
        "number_of_installments",
        "mtype",
    ]

    def __init__(
        self,
        description=APIHelper.SKIP,
        number_of_installments=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InitialPaymentMethodDto instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if number_of_installments is not APIHelper.SKIP:
            self.number_of_installments = number_of_installments
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        number_of_installments =\
            dictionary.get("number_of_installments")\
            if dictionary.get("number_of_installments")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(description,
                   number_of_installments,
                   mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _number_of_installments=(
            self.number_of_installments
            if hasattr(self, "number_of_installments")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"number_of_installments={_number_of_installments!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _number_of_installments=(
            self.number_of_installments
            if hasattr(self, "number_of_installments")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"number_of_installments={_number_of_installments!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
