"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Intent(object):
    """Implementation of the 'Intent' enum.

    Intent for the session. The field is designed to let partners inform Klarna of
    the purpose of the customer’s session.

    Attributes:
        BUY: The enum member of type str.
        TOKENIZE: The enum member of type str.
        BUY_AND_TOKENIZE: The enum member of type str.

    """

    BUY = "buy"

    TOKENIZE = "tokenize"

    BUY_AND_TOKENIZE = "buy_and_tokenize"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
