"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.link import Link


class Links(object):
    """Implementation of the 'Links' model.

    HATEOAS links to any next and/or previous pages in a pagination context.

    Attributes:
        next (Link): A URI to a resource
        prev (Link): A URI to a resource
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "next": "next",
        "prev": "prev",
    }

    _optionals = [
        "next",
        "prev",
    ]

    def __init__(
        self,
        next=APIHelper.SKIP,
        prev=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Links instance."""
        # Initialize members of the class
        if next is not APIHelper.SKIP:
            self.next = next
        if prev is not APIHelper.SKIP:
            self.prev = prev

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        next =\
            Link.from_dictionary(
                dictionary.get("next"))\
                if "next" in dictionary.keys()\
                else APIHelper.SKIP
        prev =\
            Link.from_dictionary(
                dictionary.get("prev"))\
                if "prev" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(next,
                   prev,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"next={_next!r}, "
            f"prev={_prev!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"next={_next!s}, "
            f"prev={_prev!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
