"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.address_location import AddressLocation


class Location(object):
    """Implementation of the 'Location' model.

    The location of the selected shipping option

    Attributes:
        address (AddressLocation): The address of the location
        id (str): The location id
        name (str): The display name of the location
        price (int): The price for this location
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address": "address",
        "id": "id",
        "name": "name",
        "price": "price",
    }

    _optionals = [
        "address",
        "id",
        "name",
        "price",
    ]

    def __init__(
        self,
        address=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        price=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Location instance."""
        # Initialize members of the class
        if address is not APIHelper.SKIP:
            self.address = address
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if price is not APIHelper.SKIP:
            self.price = price

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address =\
            AddressLocation.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(address,
                   id,
                   name,
                   price,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"price={_price!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"price={_price!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
