"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class MerchantUrlsV1(object):
    """Implementation of the 'MerchantUrlsV1' model.

    Attributes:
        back (str): Back URL
        cancel (str): Cancel URL
        error (str): System error URL
        failure (str): Failure URL
        status_update (str): Status update URL
        success (str): Success URL
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "back": "back",
        "cancel": "cancel",
        "error": "error",
        "failure": "failure",
        "status_update": "status_update",
        "success": "success",
    }

    _optionals = [
        "back",
        "cancel",
        "error",
        "failure",
        "status_update",
        "success",
    ]

    def __init__(
        self,
        back=APIHelper.SKIP,
        cancel=APIHelper.SKIP,
        error=APIHelper.SKIP,
        failure=APIHelper.SKIP,
        status_update=APIHelper.SKIP,
        success=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MerchantUrlsV1 instance."""
        # Initialize members of the class
        if back is not APIHelper.SKIP:
            self.back = back
        if cancel is not APIHelper.SKIP:
            self.cancel = cancel
        if error is not APIHelper.SKIP:
            self.error = error
        if failure is not APIHelper.SKIP:
            self.failure = failure
        if status_update is not APIHelper.SKIP:
            self.status_update = status_update
        if success is not APIHelper.SKIP:
            self.success = success

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        back =\
            dictionary.get("back")\
            if dictionary.get("back")\
                else APIHelper.SKIP
        cancel =\
            dictionary.get("cancel")\
            if dictionary.get("cancel")\
                else APIHelper.SKIP
        error =\
            dictionary.get("error")\
            if dictionary.get("error")\
                else APIHelper.SKIP
        failure =\
            dictionary.get("failure")\
            if dictionary.get("failure")\
                else APIHelper.SKIP
        status_update =\
            dictionary.get("status_update")\
            if dictionary.get("status_update")\
                else APIHelper.SKIP
        success =\
            dictionary.get("success")\
            if dictionary.get("success")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(back,
                   cancel,
                   error,
                   failure,
                   status_update,
                   success,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _back=(
            self.back
            if hasattr(self, "back")
            else None
        )
        _cancel=(
            self.cancel
            if hasattr(self, "cancel")
            else None
        )
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _failure=(
            self.failure
            if hasattr(self, "failure")
            else None
        )
        _status_update=(
            self.status_update
            if hasattr(self, "status_update")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"back={_back!r}, "
            f"cancel={_cancel!r}, "
            f"error={_error!r}, "
            f"failure={_failure!r}, "
            f"status_update={_status_update!r}, "
            f"success={_success!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _back=(
            self.back
            if hasattr(self, "back")
            else None
        )
        _cancel=(
            self.cancel
            if hasattr(self, "cancel")
            else None
        )
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _failure=(
            self.failure
            if hasattr(self, "failure")
            else None
        )
        _status_update=(
            self.status_update
            if hasattr(self, "status_update")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"back={_back!s}, "
            f"cancel={_cancel!s}, "
            f"error={_error!s}, "
            f"failure={_failure!s}, "
            f"status_update={_status_update!s}, "
            f"success={_success!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
