"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.payment_method_category_2 import (
    PaymentMethodCategory2,
)


class MerchantSession(object):
    """Implementation of the 'merchant_session' model.

    Attributes:
        client_token (str): Client token to be passed to the JS client while
            initializing the JS SDK in the next step.
        payment_method_categories (List[PaymentMethodCategory2]): Available payment
            method categories for this particular session
        session_id (str): ID of the created session. Please use this ID to share with
            Klarna for identifying any issues during integration.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_token": "client_token",
        "session_id": "session_id",
        "payment_method_categories": "payment_method_categories",
    }

    _optionals = [
        "payment_method_categories",
    ]

    def __init__(
        self,
        client_token=None,
        session_id=None,
        payment_method_categories=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MerchantSession instance."""
        # Initialize members of the class
        self.client_token = client_token
        if payment_method_categories is not APIHelper.SKIP:
            self.payment_method_categories = payment_method_categories
        self.session_id = session_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        client_token =\
            dictionary.get("client_token")\
            if dictionary.get("client_token")\
                else None
        session_id =\
            dictionary.get("session_id")\
            if dictionary.get("session_id")\
                else None
        payment_method_categories = None
        if dictionary.get("payment_method_categories") is not None:
            payment_method_categories = [
                PaymentMethodCategory2.from_dictionary(x)
                    for x in dictionary.get("payment_method_categories")
            ]
        else:
            payment_method_categories = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(client_token,
                   session_id,
                   payment_method_categories,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _client_token=self.client_token
        _payment_method_categories=(
            self.payment_method_categories
            if hasattr(self, "payment_method_categories")
            else None
        )
        _session_id=self.session_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_token={_client_token!r}, "
            f"payment_method_categories={_payment_method_categories!r}, "
            f"session_id={_session_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _client_token=self.client_token
        _payment_method_categories=(
            self.payment_method_categories
            if hasattr(self, "payment_method_categories")
            else None
        )
        _session_id=self.session_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"client_token={_client_token!s}, "
            f"payment_method_categories={_payment_method_categories!s}, "
            f"session_id={_session_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
