"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.customer_v_1 import CustomerV1


class MerchantManualIdentificationV1(object):
    """Implementation of the 'MerchantManualIdentificationV1' model.

    Attributes:
        challenge (str): Identification challenge
        customer (CustomerV1): The model property of type CustomerV1.
        customer_obfuscated (CustomerV1): The model property of type CustomerV1.
        expires_at (datetime): Session identification expiry time
            (YYYY-MM-ddThh:mm:ss.fffZ)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "challenge": "challenge",
        "customer": "customer",
        "customer_obfuscated": "customer_obfuscated",
        "expires_at": "expires_at",
    }

    _optionals = [
        "challenge",
        "customer",
        "customer_obfuscated",
        "expires_at",
    ]

    def __init__(
        self,
        challenge=APIHelper.SKIP,
        customer=APIHelper.SKIP,
        customer_obfuscated=APIHelper.SKIP,
        expires_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MerchantManualIdentificationV1 instance."""
        # Initialize members of the class
        if challenge is not APIHelper.SKIP:
            self.challenge = challenge
        if customer is not APIHelper.SKIP:
            self.customer = customer
        if customer_obfuscated is not APIHelper.SKIP:
            self.customer_obfuscated = customer_obfuscated
        if expires_at is not APIHelper.SKIP:
            self.expires_at =\
                 APIHelper.apply_datetime_converter(
                expires_at, APIHelper.RFC3339DateTime)\
                 if expires_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        challenge =\
            dictionary.get("challenge")\
            if dictionary.get("challenge")\
                else APIHelper.SKIP
        customer =\
            CustomerV1.from_dictionary(
                dictionary.get("customer"))\
                if "customer" in dictionary.keys()\
                else APIHelper.SKIP
        customer_obfuscated =\
            CustomerV1.from_dictionary(
                dictionary.get("customer_obfuscated"))\
                if "customer_obfuscated" in dictionary.keys()\
                else APIHelper.SKIP
        expires_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expires_at")).datetime\
            if dictionary.get("expires_at") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(challenge,
                   customer,
                   customer_obfuscated,
                   expires_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _challenge=(
            self.challenge
            if hasattr(self, "challenge")
            else None
        )
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _customer_obfuscated=(
            self.customer_obfuscated
            if hasattr(self, "customer_obfuscated")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"challenge={_challenge!r}, "
            f"customer={_customer!r}, "
            f"customer_obfuscated={_customer_obfuscated!r}, "
            f"expires_at={_expires_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _challenge=(
            self.challenge
            if hasattr(self, "challenge")
            else None
        )
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _customer_obfuscated=(
            self.customer_obfuscated
            if hasattr(self, "customer_obfuscated")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"challenge={_challenge!s}, "
            f"customer={_customer!s}, "
            f"customer_obfuscated={_customer_obfuscated!s}, "
            f"expires_at={_expires_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
