"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class OptionDto(object):
    """Implementation of the 'OptionDto' model.

    The available options and corresponding fees for extending the due date

    Attributes:
        amount (int): The fee for extending the due date this many days. In minor
            units.
        number_of_days (int): How many days to extend the due date with
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "number_of_days": "number_of_days",
    }

    _optionals = [
        "amount",
        "number_of_days",
    ]

    def __init__(
        self,
        amount=APIHelper.SKIP,
        number_of_days=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OptionDto instance."""
        # Initialize members of the class
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if number_of_days is not APIHelper.SKIP:
            self.number_of_days = number_of_days

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        number_of_days =\
            dictionary.get("number_of_days")\
            if dictionary.get("number_of_days")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(amount,
                   number_of_days,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _number_of_days=(
            self.number_of_days
            if hasattr(self, "number_of_days")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"number_of_days={_number_of_days!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _number_of_days=(
            self.number_of_days
            if hasattr(self, "number_of_days")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"number_of_days={_number_of_days!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
