"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Options(object):
    """Implementation of the 'Options' model.

    Additional configuration options for the dispute.

    Attributes:
        hold_policy (HoldPolicy): Defines when Klarna debits the Partner for any
            chargebacks and fees related to the dispute.  * `NONE` - Klarna debits
            the Partner when the dispute is closed, where relevant. *
            `ON_DISPUTE_INITIATED` - Klarna holds the chargeback and fee amount when
            the dispute moves into `INITIATED` state, and releases it again if the
            Partner wins the dispute.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "hold_policy": "hold_policy",
    }

    _optionals = [
        "hold_policy",
    ]

    def __init__(
        self,
        hold_policy=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Options instance."""
        # Initialize members of the class
        if hold_policy is not APIHelper.SKIP:
            self.hold_policy = hold_policy

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        hold_policy =\
            dictionary.get("hold_policy")\
            if dictionary.get("hold_policy")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(hold_policy,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _hold_policy=(
            self.hold_policy
            if hasattr(self, "hold_policy")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"hold_policy={_hold_policy!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _hold_policy=(
            self.hold_policy
            if hasattr(self, "hold_policy")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"hold_policy={_hold_policy!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
