"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.background_image_v_1 import (
    BackgroundImageV1,
)


class OptionsV1(object):
    """Implementation of the 'OptionsV1' model.

    Attributes:
        background_images (List[BackgroundImageV1]): List of Images to use for the
            background. Best matching resolution will be used.
        logo_url (str): URL of the logo to be displayed
        page_title (str): Title for the Payment Page
        payment_method_categories (List[PaymentMethodCategory]): Payment Method
            Categories to show on the Payment Page. All available categories will be
            given to the customer if none is specified using payment_method_category
            or payment_method_categories. Ignored field for KCO Orders.
        payment_method_category (PaymentMethodCategory1): Payment Method Category to
            show on the Payment Page. All available categories will be given to the
            customer if none is specified using payment_method_category or
            payment_method_categories. Ignored field for KCO Orders.
        place_order_mode (PlaceOrderMode): The model property of type PlaceOrderMode.
        purchase_type (PurchaseType): The type of this purchase
        show_subtotal_detail (ShowSubtotalDetail): The model property of type
            ShowSubtotalDetail.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "background_images": "background_images",
        "logo_url": "logo_url",
        "page_title": "page_title",
        "payment_method_categories": "payment_method_categories",
        "payment_method_category": "payment_method_category",
        "place_order_mode": "place_order_mode",
        "purchase_type": "purchase_type",
        "show_subtotal_detail": "show_subtotal_detail",
    }

    _optionals = [
        "background_images",
        "logo_url",
        "page_title",
        "payment_method_categories",
        "payment_method_category",
        "place_order_mode",
        "purchase_type",
        "show_subtotal_detail",
    ]

    def __init__(
        self,
        background_images=APIHelper.SKIP,
        logo_url=APIHelper.SKIP,
        page_title=APIHelper.SKIP,
        payment_method_categories=APIHelper.SKIP,
        payment_method_category=APIHelper.SKIP,
        place_order_mode=APIHelper.SKIP,
        purchase_type=APIHelper.SKIP,
        show_subtotal_detail=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OptionsV1 instance."""
        # Initialize members of the class
        if background_images is not APIHelper.SKIP:
            self.background_images = background_images
        if logo_url is not APIHelper.SKIP:
            self.logo_url = logo_url
        if page_title is not APIHelper.SKIP:
            self.page_title = page_title
        if payment_method_categories is not APIHelper.SKIP:
            self.payment_method_categories = payment_method_categories
        if payment_method_category is not APIHelper.SKIP:
            self.payment_method_category = payment_method_category
        if place_order_mode is not APIHelper.SKIP:
            self.place_order_mode = place_order_mode
        if purchase_type is not APIHelper.SKIP:
            self.purchase_type = purchase_type
        if show_subtotal_detail is not APIHelper.SKIP:
            self.show_subtotal_detail = show_subtotal_detail

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        background_images = None
        if dictionary.get("background_images") is not None:
            background_images = [
                BackgroundImageV1.from_dictionary(x)
                    for x in dictionary.get("background_images")
            ]
        else:
            background_images = APIHelper.SKIP
        logo_url =\
            dictionary.get("logo_url")\
            if dictionary.get("logo_url")\
                else APIHelper.SKIP
        page_title =\
            dictionary.get("page_title")\
            if dictionary.get("page_title")\
                else APIHelper.SKIP
        payment_method_categories =\
            dictionary.get("payment_method_categories")\
            if dictionary.get("payment_method_categories")\
                else APIHelper.SKIP
        payment_method_category =\
            dictionary.get("payment_method_category")\
            if dictionary.get("payment_method_category")\
                else APIHelper.SKIP
        place_order_mode =\
            dictionary.get("place_order_mode")\
            if dictionary.get("place_order_mode")\
                else APIHelper.SKIP
        purchase_type =\
            dictionary.get("purchase_type")\
            if dictionary.get("purchase_type")\
                else APIHelper.SKIP
        show_subtotal_detail =\
            dictionary.get("show_subtotal_detail")\
            if dictionary.get("show_subtotal_detail")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(background_images,
                   logo_url,
                   page_title,
                   payment_method_categories,
                   payment_method_category,
                   place_order_mode,
                   purchase_type,
                   show_subtotal_detail,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _background_images=(
            self.background_images
            if hasattr(self, "background_images")
            else None
        )
        _logo_url=(
            self.logo_url
            if hasattr(self, "logo_url")
            else None
        )
        _page_title=(
            self.page_title
            if hasattr(self, "page_title")
            else None
        )
        _payment_method_categories=(
            self.payment_method_categories
            if hasattr(self, "payment_method_categories")
            else None
        )
        _payment_method_category=(
            self.payment_method_category
            if hasattr(self, "payment_method_category")
            else None
        )
        _place_order_mode=(
            self.place_order_mode
            if hasattr(self, "place_order_mode")
            else None
        )
        _purchase_type=(
            self.purchase_type
            if hasattr(self, "purchase_type")
            else None
        )
        _show_subtotal_detail=(
            self.show_subtotal_detail
            if hasattr(self, "show_subtotal_detail")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"background_images={_background_images!r}, "
            f"logo_url={_logo_url!r}, "
            f"page_title={_page_title!r}, "
            f"payment_method_categories={_payment_method_categories!r}, "
            f"payment_method_category={_payment_method_category!r}, "
            f"place_order_mode={_place_order_mode!r}, "
            f"purchase_type={_purchase_type!r}, "
            f"show_subtotal_detail={_show_subtotal_detail!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _background_images=(
            self.background_images
            if hasattr(self, "background_images")
            else None
        )
        _logo_url=(
            self.logo_url
            if hasattr(self, "logo_url")
            else None
        )
        _page_title=(
            self.page_title
            if hasattr(self, "page_title")
            else None
        )
        _payment_method_categories=(
            self.payment_method_categories
            if hasattr(self, "payment_method_categories")
            else None
        )
        _payment_method_category=(
            self.payment_method_category
            if hasattr(self, "payment_method_category")
            else None
        )
        _place_order_mode=(
            self.place_order_mode
            if hasattr(self, "place_order_mode")
            else None
        )
        _purchase_type=(
            self.purchase_type
            if hasattr(self, "purchase_type")
            else None
        )
        _show_subtotal_detail=(
            self.show_subtotal_detail
            if hasattr(self, "show_subtotal_detail")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"background_images={_background_images!s}, "
            f"logo_url={_logo_url!s}, "
            f"page_title={_page_title!s}, "
            f"payment_method_categories={_payment_method_categories!s}, "
            f"payment_method_category={_payment_method_category!s}, "
            f"place_order_mode={_place_order_mode!s}, "
            f"purchase_type={_purchase_type!s}, "
            f"show_subtotal_detail={_show_subtotal_detail!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
