"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.product_identifiers import (
    ProductIdentifiers,
)
from klarna.models.subscription import Subscription


class OrderLine(object):
    """Implementation of the 'order_line' model.

    List of order lines for the capture shown to the customer.

    Attributes:
        image_url (str): URL to an image that can be embedded in communications
            between Klarna and the customer.
        merchant_data (str): Data about the order line.
        name (str): Descriptive item name.
        product_identifiers (ProductIdentifiers): product_identifiers
        product_url (str): URL to the product that can be used in communications
            between Klarna and the customer.
        quantity (int): Item quantity.
        quantity_unit (str): Unit used to describe the quantity.
        reference (str): Article number, SKU, or similar identifier on the product
            variant level.
        subscription (Subscription): Subscription information, such as the cadence
            and product name of the subscription that an order line item belongs to.
        tax_rate (int): The tax rate in percent with two implicit decimals.
        total_amount (int): Total amount including tax and discounts (`quantity *
            unit_price - total_discount_amount`).
        total_discount_amount (int): The discount amount in minor units. Includes
            tax. Example: 1200 = $12. Max value: 200000000
        total_tax_amount (int): The total tax amount in minor units.
        mtype (Type): Order line type.
        unit_price (int): Unit price including tax without applying discounts in
            minor units.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "quantity": "quantity",
        "total_amount": "total_amount",
        "unit_price": "unit_price",
        "image_url": "image_url",
        "merchant_data": "merchant_data",
        "product_identifiers": "product_identifiers",
        "product_url": "product_url",
        "quantity_unit": "quantity_unit",
        "reference": "reference",
        "subscription": "subscription",
        "tax_rate": "tax_rate",
        "total_discount_amount": "total_discount_amount",
        "total_tax_amount": "total_tax_amount",
        "mtype": "type",
    }

    _optionals = [
        "image_url",
        "merchant_data",
        "product_identifiers",
        "product_url",
        "quantity_unit",
        "reference",
        "subscription",
        "tax_rate",
        "total_discount_amount",
        "total_tax_amount",
        "mtype",
    ]

    def __init__(
        self,
        name=None,
        quantity=None,
        total_amount=None,
        unit_price=None,
        image_url=APIHelper.SKIP,
        merchant_data=APIHelper.SKIP,
        product_identifiers=APIHelper.SKIP,
        product_url=APIHelper.SKIP,
        quantity_unit=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        subscription=APIHelper.SKIP,
        tax_rate=APIHelper.SKIP,
        total_discount_amount=APIHelper.SKIP,
        total_tax_amount=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrderLine instance."""
        # Initialize members of the class
        if image_url is not APIHelper.SKIP:
            self.image_url = image_url
        if merchant_data is not APIHelper.SKIP:
            self.merchant_data = merchant_data
        self.name = name
        if product_identifiers is not APIHelper.SKIP:
            self.product_identifiers = product_identifiers
        if product_url is not APIHelper.SKIP:
            self.product_url = product_url
        self.quantity = quantity
        if quantity_unit is not APIHelper.SKIP:
            self.quantity_unit = quantity_unit
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if subscription is not APIHelper.SKIP:
            self.subscription = subscription
        if tax_rate is not APIHelper.SKIP:
            self.tax_rate = tax_rate
        self.total_amount = total_amount
        if total_discount_amount is not APIHelper.SKIP:
            self.total_discount_amount = total_discount_amount
        if total_tax_amount is not APIHelper.SKIP:
            self.total_tax_amount = total_tax_amount
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        self.unit_price = unit_price

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        total_amount =\
            dictionary.get("total_amount")\
            if dictionary.get("total_amount")\
                else None
        unit_price =\
            dictionary.get("unit_price")\
            if dictionary.get("unit_price")\
                else None
        image_url =\
            dictionary.get("image_url")\
            if dictionary.get("image_url")\
                else APIHelper.SKIP
        merchant_data =\
            dictionary.get("merchant_data")\
            if dictionary.get("merchant_data")\
                else APIHelper.SKIP
        product_identifiers =\
            ProductIdentifiers.from_dictionary(
                dictionary.get("product_identifiers"))\
                if "product_identifiers" in dictionary.keys()\
                else APIHelper.SKIP
        product_url =\
            dictionary.get("product_url")\
            if dictionary.get("product_url")\
                else APIHelper.SKIP
        quantity_unit =\
            dictionary.get("quantity_unit")\
            if dictionary.get("quantity_unit")\
                else APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        subscription =\
            Subscription.from_dictionary(
                dictionary.get("subscription"))\
                if "subscription" in dictionary.keys()\
                else APIHelper.SKIP
        tax_rate =\
            dictionary.get("tax_rate")\
            if dictionary.get("tax_rate")\
                else APIHelper.SKIP
        total_discount_amount =\
            dictionary.get("total_discount_amount")\
            if dictionary.get("total_discount_amount")\
                else APIHelper.SKIP
        total_tax_amount =\
            dictionary.get("total_tax_amount")\
            if dictionary.get("total_tax_amount")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   quantity,
                   total_amount,
                   unit_price,
                   image_url,
                   merchant_data,
                   product_identifiers,
                   product_url,
                   quantity_unit,
                   reference,
                   subscription,
                   tax_rate,
                   total_discount_amount,
                   total_tax_amount,
                   mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _merchant_data=(
            self.merchant_data
            if hasattr(self, "merchant_data")
            else None
        )
        _name=self.name
        _product_identifiers=(
            self.product_identifiers
            if hasattr(self, "product_identifiers")
            else None
        )
        _product_url=(
            self.product_url
            if hasattr(self, "product_url")
            else None
        )
        _quantity=self.quantity
        _quantity_unit=(
            self.quantity_unit
            if hasattr(self, "quantity_unit")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _subscription=(
            self.subscription
            if hasattr(self, "subscription")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _total_amount=self.total_amount
        _total_discount_amount=(
            self.total_discount_amount
            if hasattr(self, "total_discount_amount")
            else None
        )
        _total_tax_amount=(
            self.total_tax_amount
            if hasattr(self, "total_tax_amount")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _unit_price=self.unit_price
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"image_url={_image_url!r}, "
            f"merchant_data={_merchant_data!r}, "
            f"name={_name!r}, "
            f"product_identifiers={_product_identifiers!r}, "
            f"product_url={_product_url!r}, "
            f"quantity={_quantity!r}, "
            f"quantity_unit={_quantity_unit!r}, "
            f"reference={_reference!r}, "
            f"subscription={_subscription!r}, "
            f"tax_rate={_tax_rate!r}, "
            f"total_amount={_total_amount!r}, "
            f"total_discount_amount={_total_discount_amount!r}, "
            f"total_tax_amount={_total_tax_amount!r}, "
            f"mtype={_mtype!r}, "
            f"unit_price={_unit_price!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _merchant_data=(
            self.merchant_data
            if hasattr(self, "merchant_data")
            else None
        )
        _name=self.name
        _product_identifiers=(
            self.product_identifiers
            if hasattr(self, "product_identifiers")
            else None
        )
        _product_url=(
            self.product_url
            if hasattr(self, "product_url")
            else None
        )
        _quantity=self.quantity
        _quantity_unit=(
            self.quantity_unit
            if hasattr(self, "quantity_unit")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _subscription=(
            self.subscription
            if hasattr(self, "subscription")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _total_amount=self.total_amount
        _total_discount_amount=(
            self.total_discount_amount
            if hasattr(self, "total_discount_amount")
            else None
        )
        _total_tax_amount=(
            self.total_tax_amount
            if hasattr(self, "total_tax_amount")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _unit_price=self.unit_price
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"image_url={_image_url!s}, "
            f"merchant_data={_merchant_data!s}, "
            f"name={_name!s}, "
            f"product_identifiers={_product_identifiers!s}, "
            f"product_url={_product_url!s}, "
            f"quantity={_quantity!s}, "
            f"quantity_unit={_quantity_unit!s}, "
            f"reference={_reference!s}, "
            f"subscription={_subscription!s}, "
            f"tax_rate={_tax_rate!s}, "
            f"total_amount={_total_amount!s}, "
            f"total_discount_amount={_total_discount_amount!s}, "
            f"total_tax_amount={_total_tax_amount!s}, "
            f"mtype={_mtype!s}, "
            f"unit_price={_unit_price!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
