"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.authorized_payment_method import (
    AuthorizedPaymentMethod,
)


class Order(object):
    """Implementation of the 'order' model.

    Attributes:
        authorized_payment_method (AuthorizedPaymentMethod): The payment method that
            Klarna has authorized the customer for.
        fraud_status (str): Fraud status for the order. Either ACCEPTED or PENDING.
            If ACCEPTED, the order could be captured. If PENDING, please wait till
            you receive the notification from Klarna in the notification URL that the
            order has been approved. You can find additional information
            [here](https://docs.klarna.com/payments/after-payments/order-management/mo
            re-actions/pending-orders/).
        order_id (str): Unique order ID of the transaction. This ID will be used for
            all order management processes.
        redirect_url (str): URL to redirect the customer to after placing the order.
            This is a Klarna URL to which the merchant should redirect the customer
            to. Klarna will place a cookie in the customer’s browser (if redirected)
            and redirect the customer back to the confirmation URL provided by the
            merchant. This is not a mandatory step but a recommended one to improve
            the returning customer’s experience. It is a spontaneous step and does
            not harm the customer’s experience.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_id": "order_id",
        "authorized_payment_method": "authorized_payment_method",
        "fraud_status": "fraud_status",
        "redirect_url": "redirect_url",
    }

    _optionals = [
        "authorized_payment_method",
        "fraud_status",
        "redirect_url",
    ]

    def __init__(
        self,
        order_id=None,
        authorized_payment_method=APIHelper.SKIP,
        fraud_status=APIHelper.SKIP,
        redirect_url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Order instance."""
        # Initialize members of the class
        if authorized_payment_method is not APIHelper.SKIP:
            self.authorized_payment_method = authorized_payment_method
        if fraud_status is not APIHelper.SKIP:
            self.fraud_status = fraud_status
        self.order_id = order_id
        if redirect_url is not APIHelper.SKIP:
            self.redirect_url = redirect_url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else None
        authorized_payment_method =\
            AuthorizedPaymentMethod.from_dictionary(
                dictionary.get("authorized_payment_method"))\
                if "authorized_payment_method" in dictionary.keys()\
                else APIHelper.SKIP
        fraud_status =\
            dictionary.get("fraud_status")\
            if dictionary.get("fraud_status")\
                else APIHelper.SKIP
        redirect_url =\
            dictionary.get("redirect_url")\
            if dictionary.get("redirect_url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_id,
                   authorized_payment_method,
                   fraud_status,
                   redirect_url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _authorized_payment_method=(
            self.authorized_payment_method
            if hasattr(self, "authorized_payment_method")
            else None
        )
        _fraud_status=(
            self.fraud_status
            if hasattr(self, "fraud_status")
            else None
        )
        _order_id=self.order_id
        _redirect_url=(
            self.redirect_url
            if hasattr(self, "redirect_url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"authorized_payment_method={_authorized_payment_method!r}, "
            f"fraud_status={_fraud_status!r}, "
            f"order_id={_order_id!r}, "
            f"redirect_url={_redirect_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _authorized_payment_method=(
            self.authorized_payment_method
            if hasattr(self, "authorized_payment_method")
            else None
        )
        _fraud_status=(
            self.fraud_status
            if hasattr(self, "fraud_status")
            else None
        )
        _order_id=self.order_id
        _redirect_url=(
            self.redirect_url
            if hasattr(self, "redirect_url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"authorized_payment_method={_authorized_payment_method!s}, "
            f"fraud_status={_fraud_status!s}, "
            f"order_id={_order_id!s}, "
            f"redirect_url={_redirect_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
