"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Originator(object):
    """Implementation of the 'Originator' model.

    An originator is the entity that is responsible for the request.

    Attributes:
        name (str): The name of the originator using SCREAMING_SNAKE_CASE.
        session_reference (str): A reference to the session that is being used.
        module_name (str): The name of the module that is being used.
        module_version (str): The version of the module that is being used.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "session_reference": "session_reference",
        "module_name": "module_name",
        "module_version": "module_version",
    }

    _optionals = [
        "module_name",
        "module_version",
    ]

    def __init__(
        self,
        name=None,
        session_reference=None,
        module_name=APIHelper.SKIP,
        module_version=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Originator instance."""
        # Initialize members of the class
        self.name = name
        self.session_reference = session_reference
        if module_name is not APIHelper.SKIP:
            self.module_name = module_name
        if module_version is not APIHelper.SKIP:
            self.module_version = module_version

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        session_reference =\
            dictionary.get("session_reference")\
            if dictionary.get("session_reference")\
                else None
        module_name =\
            dictionary.get("module_name")\
            if dictionary.get("module_name")\
                else APIHelper.SKIP
        module_version =\
            dictionary.get("module_version")\
            if dictionary.get("module_version")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   session_reference,
                   module_name,
                   module_version,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _session_reference=self.session_reference
        _module_name=(
            self.module_name
            if hasattr(self, "module_name")
            else None
        )
        _module_version=(
            self.module_version
            if hasattr(self, "module_version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"session_reference={_session_reference!r}, "
            f"module_name={_module_name!r}, "
            f"module_version={_module_version!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _session_reference=self.session_reference
        _module_name=(
            self.module_name
            if hasattr(self, "module_name")
            else None
        )
        _module_version=(
            self.module_version
            if hasattr(self, "module_version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"session_reference={_session_reference!s}, "
            f"module_name={_module_name!s}, "
            f"module_version={_module_version!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
