"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Pagination(object):
    """Implementation of the 'Pagination' model.

    Attributes:
        count (int): The amount of elements in the current result
        total (int): The total amount of elements that are available
        next (str): The URI to the next "page" of results.
        prev (str): The URI to the previous "page" of results.
        offset (int): The current offset. Describes "where" in a collection the
            current starts.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "count": "count",
        "total": "total",
        "next": "next",
        "prev": "prev",
        "offset": "offset",
    }

    _optionals = [
        "total",
        "next",
        "prev",
        "offset",
    ]

    def __init__(
        self,
        count=None,
        total=APIHelper.SKIP,
        next=APIHelper.SKIP,
        prev=APIHelper.SKIP,
        offset=APIHelper.SKIP):
        """Initialize a Pagination instance."""
        # Initialize members of the class
        self.count = count
        if total is not APIHelper.SKIP:
            self.total = total
        if next is not APIHelper.SKIP:
            self.next = next
        if prev is not APIHelper.SKIP:
            self.prev = prev
        if offset is not APIHelper.SKIP:
            self.offset = offset

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        count =\
            dictionary.get("count")\
            if dictionary.get("count")\
                else None
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else APIHelper.SKIP
        next =\
            dictionary.get("next")\
            if dictionary.get("next")\
                else APIHelper.SKIP
        prev =\
            dictionary.get("prev")\
            if dictionary.get("prev")\
                else APIHelper.SKIP
        offset =\
            dictionary.get("offset")\
            if dictionary.get("offset")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(count,
                   total,
                   next,
                   prev,
                   offset)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _count=self.count
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _offset=(
            self.offset
            if hasattr(self, "offset")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"count={_count!r}, "
            f"total={_total!r}, "
            f"next={_next!r}, "
            f"prev={_prev!r}, "
            f"offset={_offset!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _count=self.count
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _offset=(
            self.offset
            if hasattr(self, "offset")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"count={_count!s}, "
            f"total={_total!s}, "
            f"next={_next!s}, "
            f"prev={_prev!s}, "
            f"offset={_offset!s}, "
            f")"
        )
