"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentDisputeReason(object):
    """Implementation of the 'PaymentDisputeReason' enum.

    Reason for creating the dispute. Possible values:
    - REFUND_NOT_PROCESSED: Customer claims that they returned goods or canceled
    services, but the Partner has not issued a refund to the Customer through the
    Acquiring Partners integration or Klarna's Partner Portal
    - PRODUCTS_OR_SERVICES_NOT_RECEIVED: Customer claims that they did not receive
    the goods or services because the Partner was unwilling or unable to provide the
    goods or services
    - PRODUCTS_DEFECTIVE_OR_NOT_AS_DESCRIBED: Customer claims that they received the
    goods or services, but that they deviated from what was advertised in terms of
    authenticity, condition or in other ways defective
    - PURCHASE_HIGH_RISK: Klarna identified this transaction as high risk. Cancel the
    order if possible; if already shipped, provide tracking details and attempt to
    stop delivery. Response required within 96 hours.
    - INCORRECT_AMOUNT: Customer claims to have received a charge for purchase that
    is incorrect, for example, missing discounts, unadvertised shipping fees at the
    time of purchase, incorrect items listed on the invoice, or an order amount
    already paid directly to the Partner outside of the Klarna Network
    - PURCHASE_UNAUTHORIZED: Customer claims they have never made the purchase
    - NON_COMPLIANCE: For transactions where Klarna has identified that the Partner
    has entered the Risk Program and is in Major Breach under Section 15.4 Partner
    Responsibilities and a Customer has not successfully disputed the transaction
    under another Dispute Type
    - NON_GUARANTEED_PAYMENT_PROGRAM: Klarna identified that the transaction was not
    paid by the Customer and reverses the Claim to the Acquiring Partner. Only
    applicable to the "Debit Risk" Payment Program

    Attributes:
        REFUND_NOT_PROCESSED: The enum member of type str.
        PRODUCTS_OR_SERVICES_NOT_RECEIVED: The enum member of type str.
        PRODUCTS_DEFECTIVE_OR_NOT_AS_DESCRIBED: The enum member of type str.
        INCORRECT_AMOUNT: The enum member of type str.
        PURCHASE_HIGH_RISK: The enum member of type str.
        PURCHASE_UNAUTHORIZED: The enum member of type str.
        NON_COMPLIANCE: The enum member of type str.
        NON_GUARANTEED_PAYMENT_PROGRAM: The enum member of type str.

    """

    _all_values = ["REFUND_NOT_PROCESSED", "PRODUCTS_OR_SERVICES_NOT_RECEIVED",
        "PRODUCTS_DEFECTIVE_OR_NOT_AS_DESCRIBED", "INCORRECT_AMOUNT",
        "PURCHASE_HIGH_RISK", "PURCHASE_UNAUTHORIZED", "NON_COMPLIANCE",
        "NON_GUARANTEED_PAYMENT_PROGRAM"]
    REFUND_NOT_PROCESSED = "REFUND_NOT_PROCESSED"

    PRODUCTS_OR_SERVICES_NOT_RECEIVED = "PRODUCTS_OR_SERVICES_NOT_RECEIVED"

    PRODUCTS_DEFECTIVE_OR_NOT_AS_DESCRIBED = "PRODUCTS_DEFECTIVE_OR_NOT_AS_DESCRIBED"

    INCORRECT_AMOUNT = "INCORRECT_AMOUNT"

    PURCHASE_HIGH_RISK = "PURCHASE_HIGH_RISK"

    PURCHASE_UNAUTHORIZED = "PURCHASE_UNAUTHORIZED"

    NON_COMPLIANCE = "NON_COMPLIANCE"

    NON_GUARANTEED_PAYMENT_PROGRAM = "NON_GUARANTEED_PAYMENT_PROGRAM"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
