"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class PaymentDisputeAttachment(object):
    """Implementation of the 'PaymentDisputeAttachment' model.

    Attachment linked to the dispute

    Attributes:
        payment_dispute_attachment_id (str): Unique identifier for the payment
            dispute attachment
        description (str): Optional description of the attachment

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_dispute_attachment_id": "payment_dispute_attachment_id",
        "description": "description",
    }

    _optionals = [
        "description",
    ]

    def __init__(
        self,
        payment_dispute_attachment_id=None,
        description=APIHelper.SKIP):
        """Initialize a PaymentDisputeAttachment instance."""
        # Initialize members of the class
        self.payment_dispute_attachment_id = payment_dispute_attachment_id
        if description is not APIHelper.SKIP:
            self.description = description

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_dispute_attachment_id =\
            dictionary.get("payment_dispute_attachment_id")\
            if dictionary.get("payment_dispute_attachment_id")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(payment_dispute_attachment_id,
                   description)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!r}, "
            f"description={_description!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!s}, "
            f"description={_description!s}, "
            f")"
        )
