"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class PaymentDisputeFlowDisputeWindowExtensionExceptions(object):
    """Implementation of the
    'PaymentDisputeFlowDisputeWindowExtensionExceptions' model.

    Exceptions that extend the dispute window beyond the standard timeframe, allowing
    disputes to be opened outside the regular dispute opening period.

    Attributes:
        exception_type (str): The type of exception indicating the dispute window has
            been extended. This is an open enum - clients should handle unknown
            values gracefully as new values may be added in the future.  **Open Enum
            - values:**  | Value | Description | |-------|-------------| |
            `dispute_window_extension` | Dispute window has been extended beyond the
            standard timeframe |
        reason (str): The specific reason for extending the dispute window. This is
            an open enum - clients should handle unknown values gracefully as new
            values may be added in the future.  **Open Enum - values:**  | Value |
            Description | |-------|-------------| | `dispute_mis_handled` | Dispute
            window extended due to errors or mishandling in the previous dispute
            process | | `regulatory_requirement` | Dispute window extended to comply
            with applicable legal or regulatory obligations |
        description (str): Human-readable explanation of why the exception was
            applied. The description text should match the reason value as documented
            above.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "exception_type": "exception_type",
        "reason": "reason",
        "description": "description",
    }

    def __init__(
        self,
        exception_type=None,
        reason=None,
        description=None,
        additional_properties=None):
        """Initialize a PaymentDisputeFlowDisputeWindowExtensionExceptions instance."""
        # Initialize members of the class
        self.exception_type = exception_type
        self.reason = reason
        self.description = description

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        exception_type =\
            dictionary.get("exception_type")\
            if dictionary.get("exception_type")\
                else None
        reason =\
            dictionary.get("reason")\
            if dictionary.get("reason")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(exception_type,
                   reason,
                   description,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.exception_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.reason,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.description,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("exception_type"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("reason"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("description"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _exception_type=self.exception_type
        _reason=self.reason
        _description=self.description
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"exception_type={_exception_type!r}, "
            f"reason={_reason!r}, "
            f"description={_description!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _exception_type=self.exception_type
        _reason=self.reason
        _description=self.description
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"exception_type={_exception_type!s}, "
            f"reason={_reason!s}, "
            f"description={_description!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
