"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentMethodCategory1(object):
    """Implementation of the 'PaymentMethodCategory1' enum.

    Payment Method Category to show on the Payment Page. All available categories
    will be given to the customer if none is specified using payment_method_category
    or payment_method_categories. Ignored field for KCO Orders.

    Attributes:
        DIRECT_DEBIT: The enum member of type str.
        DIRECT_BANK_TRANSFER: The enum member of type str.
        PAY_NOW: The enum member of type str.
        PAY_LATER: The enum member of type str.
        PAY_OVER_TIME: The enum member of type str.
        KLARNA: The enum member of type str.

    """

    DIRECT_DEBIT = "DIRECT_DEBIT"

    DIRECT_BANK_TRANSFER = "DIRECT_BANK_TRANSFER"

    PAY_NOW = "PAY_NOW"

    PAY_LATER = "PAY_LATER"

    PAY_OVER_TIME = "PAY_OVER_TIME"

    KLARNA = "KLARNA"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
