"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.arbitration_preliminary_outcome import (
    ArbitrationPreliminaryOutcome,
)
from klarna.models.payment_dispute_arbitration_request import (
    PaymentDisputeArbitrationRequest,
)


class PaymentDisputeArbitrationDetailsBase(object):
    """Implementation of the 'PaymentDisputeArbitrationDetailsBase' model.

    Details specific to the arbitration process

    Attributes:
        preliminary_outcome (ArbitrationPreliminaryOutcome): Preliminary outcome of
            the arbitration. Possible values: - WON: Partner won the dispute - LOST:
            Partner lost the dispute
        preliminary_outcome_detailed (str): Detailed outcome of the dispute closure.
            This is an open enum - clients should handle unknown values gracefully as
            new values may be added in the future.  **Open Enum - values:**  | Value
            | Description | |-------|-------------| |
            `partner_did_not_reply_to_dispute_request` | Partner did not reply to
            dispute request | | `partner_did_not_follow_klarnas_shipping_policy` |
            Partner did not follow Klarna's shipping policy | |
            `partner_did_not_adjust_statement_on_klarnas_request` | Partner did not
            adjust statement on Klarna's request | | `shipped_stop_requested_order` |
            Shipped stop requested order | | `invoice_incorrectly_activated` |
            Invoice incorrectly activated | | `order_missing_consumer_details` |
            Order missing consumer details | | `shipped_to_non_approved_address` |
            Shipped to non-approved address | |
            `incorrect_invalid_delivery_in_physical_store` | Incorrect invalid
            delivery in physical store | |
            `service_digital_goods_klarna_does_not_take_risk` | Service digital goods
            Klarna does not take risk | | `partner_provided_valid_shipping_details` |
            Partner provided valid shipping details | |
            `partner_informed_about_invalid_return` | Partner informed about invalid
            return | | `partner_informs_that_invoice_is_correct` | Partner informs
            that invoice is correct | |
            `partner_has_not_received_payment_or_payment_to_3rd_party` | Partner has
            not received payment or payment to 3rd party | |
            `partner_has_refunded_payment_to_customer` | Partner has refunded payment
            to customer | | `partner_solved_the_dispute_with_the_customer` | Partner
            solved the dispute with the customer | |
            `partner_informed_about_invalid_dispute` | Partner informed about invalid
            dispute | | `reactivated_invoice_statement` | Reactivated invoice
            statement | | `customer_cancelled_dispute` | Customer cancelled dispute |
            | `incorrect_payment_details_used_refunded` | Incorrect payment details
            used refunded | | `fully_paid_after_escalation` | Fully paid after
            escalation | | `refund_issued_by_partner_after_escalation` | Refund
            issued by partner after escalation | | `partner_accepted_the_loss` |
            Partner accepted the loss | | `non_approved_address_recipient` |
            Non-approved address recipient | | `insufficient_proof_of_delivery` |
            Insufficient proof of delivery | | `non_physical_goods` | Non-physical
            goods | | `insufficient_recipient_check_at_pickup_delivery` |
            Insufficient recipient check at pickup delivery | |
            `partner_did_not_respond_to_stop_request` | Partner did not respond to
            stop request | | `no_proof_of_delivery` | No proof of delivery | |
            `partner_successfully_canceled_full_order` | Partner successfully
            canceled full order | | `partner_successfully_canceled_partial_order` |
            Partner successfully canceled partial order | |
            `partner_did_not_respond_but_provided_full_shipping_information_when_order
            _was_captured` | Partner did not respond but provided full shipping
            information when order was captured | |
            `partner_did_not_respond_but_provided_partial_shipping_information_when_or
            der_was_captured` | Partner did not respond but provided partial shipping
            information when order was captured | |
            `partner_did_not_respond_and_did_not_provide_shipping_information_when_ord
            er_was_captured` | Partner did not respond and did not provide shipping
            information when order was captured | |
            `partner_captured_full_order_but_provided_full_shipping_information_via_re
            sponse` | Partner captured full order but provided full shipping
            information via response | |
            `partner_captured_full_order_but_provided_partial_shipping_information_via
            _response` | Partner captured full order but provided partial shipping
            information via response | |
            `partner_responded_but_the_order_was_sent_without_shipping_information` |
            Partner responded but the order was sent without shipping information | |
            `partner_claimed_they_would_cancel_the_order_but_did_not` | Partner
            claimed they would cancel the order but did not | |
            `partner_captured_partial_order_but_provided_shipping_information_via_resp
            onse` | Partner captured partial order but provided shipping information
            via response | | `partner_did_not_perform_promised_refund` | Partner did
            not perform promised refund | |
            `klarna_resolved_dispute_in_partner_favor` | Klarna resolved dispute in
            partner favor | | `could_not_send_another_request` | Could not send
            another request | | `klarna_resolved_due_wrong_dispute_reason_chosen` |
            Klarna resolved due wrong dispute reason chosen | |
            `dispute_opened_under_wrong_dispute_reason` | Dispute opened under wrong
            dispute reason | | `partner_did_not_update_order_as_requested` | Partner
            did not update order as requested |
        arbitration_request (PaymentDisputeArbitrationRequest): Captures the
            Partner's appeal against a preliminary arbitration decision, including
            the written explanation and any supporting evidence files.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "preliminary_outcome": "preliminary_outcome",
        "preliminary_outcome_detailed": "preliminary_outcome_detailed",
        "arbitration_request": "arbitration_request",
    }

    _optionals = [
        "arbitration_request",
    ]

    def __init__(
        self,
        preliminary_outcome=None,
        preliminary_outcome_detailed=None,
        arbitration_request=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentDisputeArbitrationDetailsBase instance."""
        # Initialize members of the class
        self.preliminary_outcome = preliminary_outcome
        self.preliminary_outcome_detailed = preliminary_outcome_detailed
        if arbitration_request is not APIHelper.SKIP:
            self.arbitration_request = arbitration_request

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        preliminary_outcome =\
            dictionary.get("preliminary_outcome")\
            if dictionary.get("preliminary_outcome")\
                else None
        preliminary_outcome_detailed =\
            dictionary.get("preliminary_outcome_detailed")\
            if dictionary.get("preliminary_outcome_detailed")\
                else None
        arbitration_request =\
            PaymentDisputeArbitrationRequest.from_dictionary(
                dictionary.get("arbitration_request"))\
                if "arbitration_request" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(preliminary_outcome,
                   preliminary_outcome_detailed,
                   arbitration_request,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.preliminary_outcome,
                    type_callable=lambda value:
                        ArbitrationPreliminaryOutcome.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.preliminary_outcome_detailed,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("preliminary_outcome"),
                type_callable=lambda value:
                    ArbitrationPreliminaryOutcome.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("preliminary_outcome_detailed"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _preliminary_outcome=self.preliminary_outcome
        _preliminary_outcome_detailed=self.preliminary_outcome_detailed
        _arbitration_request=(
            self.arbitration_request
            if hasattr(self, "arbitration_request")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"preliminary_outcome={_preliminary_outcome!r}, "
            f"preliminary_outcome_detailed={_preliminary_outcome_detailed!r}, "
            f"arbitration_request={_arbitration_request!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _preliminary_outcome=self.preliminary_outcome
        _preliminary_outcome_detailed=self.preliminary_outcome_detailed
        _arbitration_request=(
            self.arbitration_request
            if hasattr(self, "arbitration_request")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"preliminary_outcome={_preliminary_outcome!s}, "
            f"preliminary_outcome_detailed={_preliminary_outcome_detailed!s}, "
            f"arbitration_request={_arbitration_request!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
