"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class PaymentDisputeNewAttachmentBody(object):
    """Implementation of the 'PaymentDisputeNewAttachmentBody' model.

    New file attachment upload to be linked to a dispute response. This endpoint uses
    multipart/form-data for file uploads.

    Attributes:
        filename (str): Optional filename for the uploaded attachment. If not
            provided, the original filename from the uploaded file will be used. If
            provided, the file extension must match the extension of the uploaded
            file. Maximum length is 1000 characters (excluding the file extension).
        file (binary): The file to upload as binary data. This field is required and
            must contain the actual file content. Supported file types are: PDF
            (.pdf), JPEG (.jpg, .jpeg), PNG (.png), and Word documents (.docx).
            Maximum file size is 7MB.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "file": "file",
        "filename": "filename",
    }

    _optionals = [
        "filename",
    ]

    def __init__(
        self,
        file=None,
        filename=APIHelper.SKIP):
        """Initialize a PaymentDisputeNewAttachmentBody instance."""
        # Initialize members of the class
        if filename is not APIHelper.SKIP:
            self.filename = filename
        self.file = file

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        file =\
            dictionary.get("file")\
            if dictionary.get("file")\
                else None
        filename =\
            dictionary.get("filename")\
            if dictionary.get("filename")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(file,
                   filename)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _filename=(
            self.filename
            if hasattr(self, "filename")
            else None
        )
        _file=self.file
        return (
            f"{self.__class__.__name__}("
            f"filename={_filename!r}, "
            f"file={_file!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _filename=(
            self.filename
            if hasattr(self, "filename")
            else None
        )
        _file=self.file
        return (
            f"{self.__class__.__name__}("
            f"filename={_filename!s}, "
            f"file={_file!s}, "
            f")"
        )
