"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentDisputeRepresentmentState(object):
    """Implementation of the 'PaymentDisputeRepresentmentState' enum.

    The current state of the Dispute Evidence Request.
    * `EVIDENCE_REQUESTED` - Partner can reply to the request.
    * `EVIDENCE_RECEIVED` - Evidence is being reviewed by Klarna, it's not possible
    to reply to the request.
    * `EVIDENCE_REQUEST_EXPIRED` - Request time expired, it's not possible to reply
    to the request. The dispute will result in outcome LOST if partner does not
    respond before the deadline.
    * `EVIDENCE_WAIVED` - Partner accepted the dispute loss in INITIATED state using
    the accept-loss endpoint. No further action possible.
    * `REPRESENTMENT_AUTOMATICALLY_REJECTED` - Dispute representment automatically
    rejected because the dispute amount falls below the partner's configured
    threshold. Disputes below this threshold are automatically accepted as LOST. No
    further action possible.

    Attributes:
        EVIDENCE_REQUESTED: The enum member of type str.
        EVIDENCE_RECEIVED: The enum member of type str.
        EVIDENCE_REQUEST_EXPIRED: The enum member of type str.
        EVIDENCE_WAIVED: The enum member of type str.
        REPRESENTMENT_AUTOMATICALLY_REJECTED: The enum member of type str.

    """

    _all_values = ["EVIDENCE_REQUESTED", "EVIDENCE_RECEIVED", "EVIDENCE_REQUEST_EXPIRED",
        "EVIDENCE_WAIVED", "REPRESENTMENT_AUTOMATICALLY_REJECTED"]
    EVIDENCE_REQUESTED = "EVIDENCE_REQUESTED"

    EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED"

    EVIDENCE_REQUEST_EXPIRED = "EVIDENCE_REQUEST_EXPIRED"

    EVIDENCE_WAIVED = "EVIDENCE_WAIVED"

    REPRESENTMENT_AUTOMATICALLY_REJECTED = "REPRESENTMENT_AUTOMATICALLY_REJECTED"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
