"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PaymentDisputeNewAttachmentResponse(object):
    """Implementation of the 'PaymentDisputeNewAttachmentResponse' model.

    New file attachment upload response

    Attributes:
        payment_dispute_attachment_id (str): Unique attachment identifier obtained
            after uploading of an attachment

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_dispute_attachment_id": "payment_dispute_attachment_id",
    }

    def __init__(
        self,
        payment_dispute_attachment_id=None):
        """Initialize a PaymentDisputeNewAttachmentResponse instance."""
        # Initialize members of the class
        self.payment_dispute_attachment_id = payment_dispute_attachment_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_dispute_attachment_id =\
            dictionary.get("payment_dispute_attachment_id")\
            if dictionary.get("payment_dispute_attachment_id")\
                else None

        # Return an object of this model
        return cls(payment_dispute_attachment_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_dispute_attachment_id=self.payment_dispute_attachment_id
        return (
            f"{self.__class__.__name__}("
            f"payment_dispute_attachment_id={_payment_dispute_attachment_id!s}, "
            f")"
        )
