"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.webhook_metadata import WebhookMetadata


class PaymentDisputeStateChange(object):
    """Implementation of the 'payment.dispute.state-change' model.

    The payment dispute state change webhook is triggered when the state of a payment
    dispute changes (aligned with Visa Claims Resolution lifecycle).

    Attributes:
        event_type (EventType): The model property of type EventType.
        event_id (uuid|str): Unique identifier
        occurred_at (datetime): The timestamp when the webhook event occurred. In ISO
            8601 with timezone e.g. 2024-01-01T12:00:00Z
        metadata (WebhookMetadata): The metadata of the webhook event.
        payload (PaymentDisputeStateChangeInitiated |
            PaymentDisputeStateChangeRepresentment |
            PaymentDisputeStateChangePreArbitration |
            PaymentDisputeStateChangeArbitration | PaymentDisputeStateChangeClosed |
            None): The payload of the payment dispute state change webhook.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "event_type": "event_type",
        "event_id": "event_id",
        "occurred_at": "occurred_at",
        "metadata": "metadata",
        "payload": "payload",
    }

    _optionals = [
        "event_type",
        "event_id",
        "occurred_at",
        "metadata",
        "payload",
    ]

    def __init__(
        self,
        event_type=APIHelper.SKIP,
        event_id=APIHelper.SKIP,
        occurred_at=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        payload=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentDisputeStateChange instance."""
        # Initialize members of the class
        if event_type is not APIHelper.SKIP:
            self.event_type = event_type
        if event_id is not APIHelper.SKIP:
            self.event_id = event_id
        if occurred_at is not APIHelper.SKIP:
            self.occurred_at =\
                 APIHelper.apply_datetime_converter(
                occurred_at, APIHelper.RFC3339DateTime)\
                 if occurred_at else None
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if payload is not APIHelper.SKIP:
            self.payload = payload

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from klarna.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        event_type =\
            dictionary.get("event_type")\
            if dictionary.get("event_type")\
                else APIHelper.SKIP
        event_id =\
            dictionary.get("event_id")\
            if dictionary.get("event_id")\
                else APIHelper.SKIP
        occurred_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("occurred_at")).datetime\
            if dictionary.get("occurred_at") else APIHelper.SKIP
        metadata =\
            WebhookMetadata.from_dictionary(
                dictionary.get("metadata"))\
                if "metadata" in dictionary.keys()\
                else APIHelper.SKIP
        payload = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PaymentDisputeStateChangePayload"),
            dictionary.get("payload"),
            False)\
            if dictionary.get("payload") is not None\
            else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(event_type,
                   event_id,
                   occurred_at,
                   metadata,
                   payload,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _event_type=(
            self.event_type
            if hasattr(self, "event_type")
            else None
        )
        _event_id=(
            self.event_id
            if hasattr(self, "event_id")
            else None
        )
        _occurred_at=(
            self.occurred_at
            if hasattr(self, "occurred_at")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _payload=(
            self.payload
            if hasattr(self, "payload")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"event_type={_event_type!r}, "
            f"event_id={_event_id!r}, "
            f"occurred_at={_occurred_at!r}, "
            f"metadata={_metadata!r}, "
            f"payload={_payload!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _event_type=(
            self.event_type
            if hasattr(self, "event_type")
            else None
        )
        _event_id=(
            self.event_id
            if hasattr(self, "event_id")
            else None
        )
        _occurred_at=(
            self.occurred_at
            if hasattr(self, "occurred_at")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _payload=(
            self.payload
            if hasattr(self, "payload")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"event_type={_event_type!s}, "
            f"event_id={_event_id!s}, "
            f"occurred_at={_occurred_at!s}, "
            f"metadata={_metadata!s}, "
            f"payload={_payload!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
