"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class PayoutSummary(object):
    """Implementation of the 'PayoutSummary' model.

    Attributes:
        summary_total_fee_correction_amount (int): The total amount of fee
            correction, in minor units
        summary_payout_date_start (datetime): ISO 8601 formatted date-time string
        summary_total_release_amount (int): The total amount of money released from
            holdback by Klarna, in minor units
        summary_settlement_currency (str): ISO 4217 Currency Code. Like USD, EUR, AUD
            or GBP.
        summary_payout_date_end (datetime): ISO 8601 formatted date-time string
        summary_total_tax_amount (int): The total amount of tax, in minor units
        summary_total_settlement_amount (int): The total amount of the settlement in
            question, in minor units
        summary_total_holdback_amount (int): The total amount of money withheld by
            Klarna, in minor units
        summary_total_reversal_amount (int): The total amount of reversals, in minor
            units
        summary_total_return_amount (int): The total amount of returns, in minor units
        summary_total_fee_amount (int): The total amount of fees, in minor units
        summary_total_commission_amount (int): The total amount of commissions, in
            minor units
        summary_total_commission_reversal_amount (int): The total amount of
            commission reversals, in minor units
        summary_total_sale_amount (int): The total amount of sales, in minor units
        summary_total_repay_amount (int): The total amount of money that has been
            repaid by the merchant from the debt to Klarna, in minor units

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "summary_total_fee_correction_amount": "summary_total_fee_correction_amount",
        "summary_payout_date_start": "summary_payout_date_start",
        "summary_total_release_amount": "summary_total_release_amount",
        "summary_settlement_currency": "summary_settlement_currency",
        "summary_payout_date_end": "summary_payout_date_end",
        "summary_total_tax_amount": "summary_total_tax_amount",
        "summary_total_settlement_amount": "summary_total_settlement_amount",
        "summary_total_holdback_amount": "summary_total_holdback_amount",
        "summary_total_reversal_amount": "summary_total_reversal_amount",
        "summary_total_return_amount": "summary_total_return_amount",
        "summary_total_fee_amount": "summary_total_fee_amount",
        "summary_total_commission_amount": "summary_total_commission_amount",
        "summary_total_sale_amount": "summary_total_sale_amount",
        "summary_total_repay_amount": "summary_total_repay_amount",
        "summary_total_commission_reversal_amount":
            "summary_total_commission_reversal_amount",
    }

    _optionals = [
        "summary_total_commission_reversal_amount",
    ]

    def __init__(
        self,
        summary_total_fee_correction_amount=None,
        summary_payout_date_start=None,
        summary_total_release_amount=None,
        summary_settlement_currency=None,
        summary_payout_date_end=None,
        summary_total_tax_amount=None,
        summary_total_settlement_amount=None,
        summary_total_holdback_amount=None,
        summary_total_reversal_amount=None,
        summary_total_return_amount=None,
        summary_total_fee_amount=None,
        summary_total_commission_amount=None,
        summary_total_sale_amount=None,
        summary_total_repay_amount=None,
        summary_total_commission_reversal_amount=APIHelper.SKIP):
        """Initialize a PayoutSummary instance."""
        # Initialize members of the class
        self.summary_total_fee_correction_amount =\
             summary_total_fee_correction_amount
        self.summary_payout_date_start =\
             APIHelper.apply_datetime_converter(
            summary_payout_date_start, APIHelper.RFC3339DateTime)\
             if summary_payout_date_start else None
        self.summary_total_release_amount = summary_total_release_amount
        self.summary_settlement_currency = summary_settlement_currency
        self.summary_payout_date_end =\
             APIHelper.apply_datetime_converter(
            summary_payout_date_end, APIHelper.RFC3339DateTime)\
             if summary_payout_date_end else None
        self.summary_total_tax_amount = summary_total_tax_amount
        self.summary_total_settlement_amount = summary_total_settlement_amount
        self.summary_total_holdback_amount = summary_total_holdback_amount
        self.summary_total_reversal_amount = summary_total_reversal_amount
        self.summary_total_return_amount = summary_total_return_amount
        self.summary_total_fee_amount = summary_total_fee_amount
        self.summary_total_commission_amount = summary_total_commission_amount
        if summary_total_commission_reversal_amount is not APIHelper.SKIP:
            self.summary_total_commission_reversal_amount =\
                 summary_total_commission_reversal_amount
        self.summary_total_sale_amount = summary_total_sale_amount
        self.summary_total_repay_amount = summary_total_repay_amount

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        summary_total_fee_correction_amount =\
            dictionary.get("summary_total_fee_correction_amount")\
            if dictionary.get("summary_total_fee_correction_amount")\
                else None
        summary_payout_date_start = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("summary_payout_date_start")).datetime\
            if dictionary.get("summary_payout_date_start") else None
        summary_total_release_amount =\
            dictionary.get("summary_total_release_amount")\
            if dictionary.get("summary_total_release_amount")\
                else None
        summary_settlement_currency =\
            dictionary.get("summary_settlement_currency")\
            if dictionary.get("summary_settlement_currency")\
                else None
        summary_payout_date_end = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("summary_payout_date_end")).datetime\
            if dictionary.get("summary_payout_date_end") else None
        summary_total_tax_amount =\
            dictionary.get("summary_total_tax_amount")\
            if dictionary.get("summary_total_tax_amount")\
                else None
        summary_total_settlement_amount =\
            dictionary.get("summary_total_settlement_amount")\
            if dictionary.get("summary_total_settlement_amount")\
                else None
        summary_total_holdback_amount =\
            dictionary.get("summary_total_holdback_amount")\
            if dictionary.get("summary_total_holdback_amount")\
                else None
        summary_total_reversal_amount =\
            dictionary.get("summary_total_reversal_amount")\
            if dictionary.get("summary_total_reversal_amount")\
                else None
        summary_total_return_amount =\
            dictionary.get("summary_total_return_amount")\
            if dictionary.get("summary_total_return_amount")\
                else None
        summary_total_fee_amount =\
            dictionary.get("summary_total_fee_amount")\
            if dictionary.get("summary_total_fee_amount")\
                else None
        summary_total_commission_amount =\
            dictionary.get("summary_total_commission_amount")\
            if dictionary.get("summary_total_commission_amount")\
                else None
        summary_total_sale_amount =\
            dictionary.get("summary_total_sale_amount")\
            if dictionary.get("summary_total_sale_amount")\
                else None
        summary_total_repay_amount =\
            dictionary.get("summary_total_repay_amount")\
            if dictionary.get("summary_total_repay_amount")\
                else None
        summary_total_commission_reversal_amount =\
            dictionary.get("summary_total_commission_reversal_amount")\
            if dictionary.get("summary_total_commission_reversal_amount")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(summary_total_fee_correction_amount,
                   summary_payout_date_start,
                   summary_total_release_amount,
                   summary_settlement_currency,
                   summary_payout_date_end,
                   summary_total_tax_amount,
                   summary_total_settlement_amount,
                   summary_total_holdback_amount,
                   summary_total_reversal_amount,
                   summary_total_return_amount,
                   summary_total_fee_amount,
                   summary_total_commission_amount,
                   summary_total_sale_amount,
                   summary_total_repay_amount,
                   summary_total_commission_reversal_amount)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _summary_total_fee_correction_amount=self.summary_total_fee_correction_amount
        _summary_payout_date_start=self.summary_payout_date_start
        _summary_total_release_amount=self.summary_total_release_amount
        _summary_settlement_currency=self.summary_settlement_currency
        _summary_payout_date_end=self.summary_payout_date_end
        _summary_total_tax_amount=self.summary_total_tax_amount
        _summary_total_settlement_amount=self.summary_total_settlement_amount
        _summary_total_holdback_amount=self.summary_total_holdback_amount
        _summary_total_reversal_amount=self.summary_total_reversal_amount
        _summary_total_return_amount=self.summary_total_return_amount
        _summary_total_fee_amount=self.summary_total_fee_amount
        _summary_total_commission_amount=self.summary_total_commission_amount
        _summary_total_commission_reversal_amount=(
            self.summary_total_commission_reversal_amount
            if hasattr(self, "summary_total_commission_reversal_amount")
            else None
        )
        _summary_total_sale_amount=self.summary_total_sale_amount
        _summary_total_repay_amount=self.summary_total_repay_amount
        return (
            f"{self.__class__.__name__}("
            f"summary_total_fee_correction_amount={_summary_total_fee_correction_amount!r}, "
            f"summary_payout_date_start={_summary_payout_date_start!r}, "
            f"summary_total_release_amount={_summary_total_release_amount!r}, "
            f"summary_settlement_currency={_summary_settlement_currency!r}, "
            f"summary_payout_date_end={_summary_payout_date_end!r}, "
            f"summary_total_tax_amount={_summary_total_tax_amount!r}, "
            f"summary_total_settlement_amount={_summary_total_settlement_amount!r}, "
            f"summary_total_holdback_amount={_summary_total_holdback_amount!r}, "
            f"summary_total_reversal_amount={_summary_total_reversal_amount!r}, "
            f"summary_total_return_amount={_summary_total_return_amount!r}, "
            f"summary_total_fee_amount={_summary_total_fee_amount!r}, "
            f"summary_total_commission_amount={_summary_total_commission_amount!r}, "
            f"summary_total_commission_reversal_amount={_summary_total_commission_reversal_amount!r}, "
            f"summary_total_sale_amount={_summary_total_sale_amount!r}, "
            f"summary_total_repay_amount={_summary_total_repay_amount!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _summary_total_fee_correction_amount=self.summary_total_fee_correction_amount
        _summary_payout_date_start=self.summary_payout_date_start
        _summary_total_release_amount=self.summary_total_release_amount
        _summary_settlement_currency=self.summary_settlement_currency
        _summary_payout_date_end=self.summary_payout_date_end
        _summary_total_tax_amount=self.summary_total_tax_amount
        _summary_total_settlement_amount=self.summary_total_settlement_amount
        _summary_total_holdback_amount=self.summary_total_holdback_amount
        _summary_total_reversal_amount=self.summary_total_reversal_amount
        _summary_total_return_amount=self.summary_total_return_amount
        _summary_total_fee_amount=self.summary_total_fee_amount
        _summary_total_commission_amount=self.summary_total_commission_amount
        _summary_total_commission_reversal_amount=(
            self.summary_total_commission_reversal_amount
            if hasattr(self, "summary_total_commission_reversal_amount")
            else None
        )
        _summary_total_sale_amount=self.summary_total_sale_amount
        _summary_total_repay_amount=self.summary_total_repay_amount
        return (
            f"{self.__class__.__name__}("
            f"summary_total_fee_correction_amount={_summary_total_fee_correction_amount!s}, "
            f"summary_payout_date_start={_summary_payout_date_start!s}, "
            f"summary_total_release_amount={_summary_total_release_amount!s}, "
            f"summary_settlement_currency={_summary_settlement_currency!s}, "
            f"summary_payout_date_end={_summary_payout_date_end!s}, "
            f"summary_total_tax_amount={_summary_total_tax_amount!s}, "
            f"summary_total_settlement_amount={_summary_total_settlement_amount!s}, "
            f"summary_total_holdback_amount={_summary_total_holdback_amount!s}, "
            f"summary_total_reversal_amount={_summary_total_reversal_amount!s}, "
            f"summary_total_return_amount={_summary_total_return_amount!s}, "
            f"summary_total_fee_amount={_summary_total_fee_amount!s}, "
            f"summary_total_commission_amount={_summary_total_commission_amount!s}, "
            f"summary_total_commission_reversal_amount={_summary_total_commission_reversal_amount!s}, "
            f"summary_total_sale_amount={_summary_total_sale_amount!s}, "
            f"summary_total_repay_amount={_summary_total_repay_amount!s}, "
            f")"
        )
