"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.card_specification import (
    CardSpecification,
)


class PromiseRequest(object):
    """Implementation of the 'promise_request' model.

    Attributes:
        order_id (str): A valid order id
        cards (List[CardSpecification]): The cards you would like to issue (max 1000)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_id": "order_id",
        "cards": "cards",
    }

    def __init__(
        self,
        order_id=None,
        cards=None,
        additional_properties=None):
        """Initialize a PromiseRequest instance."""
        # Initialize members of the class
        self.order_id = order_id
        self.cards = cards

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else None
        cards = None
        if dictionary.get("cards") is not None:
            cards = [
                CardSpecification.from_dictionary(x)
                    for x in dictionary.get("cards")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_id,
                   cards,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _order_id=self.order_id
        _cards=self.cards
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!r}, "
            f"cards={_cards!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _order_id=self.order_id
        _cards=self.cards
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!s}, "
            f"cards={_cards!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
