"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PurchaseType(object):
    """Implementation of the 'PurchaseType' enum.

    The type of this purchase

    Attributes:
        BUY: The enum member of type str.
        RENT: The enum member of type str.
        BOOK: The enum member of type str.
        SUBSCRIBE: The enum member of type str.
        DOWNLOAD: The enum member of type str.
        ORDER: The enum member of type str.
        CONTINUE: The enum member of type str.

    """

    BUY = "BUY"

    RENT = "RENT"

    BOOK = "BOOK"

    SUBSCRIBE = "SUBSCRIBE"

    DOWNLOAD = "DOWNLOAD"

    ORDER = "ORDER"

    CONTINUE = "CONTINUE"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
