"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ReasonCode(object):
    """Implementation of the 'ReasonCode' enum.

    Reason code for why the order cancellation was rejected.
    This field is only populated if status is `REJECTED`.

    Attributes:
        CARD_IN_USE: The enum member of type str.
        OTHER: The enum member of type str.

    """

    CARD_IN_USE = "CARD_IN_USE"

    OTHER = "OTHER"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
