"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.order_line import OrderLine


class Refund(object):
    """Implementation of the 'Refund' model.

    Attributes:
        credit_invoice (bool): Only relevant for B2B Orders. If the flag is set to
            true for an order with B2B_invoice as payment method, the customer will
            receive the refund as a credit invoice.
        description (str): Description of the refund shown to the customer. Max
            length is 255 characters.
        order_lines (List[OrderLine]): Order lines for the refund shown to the
            customer. Optional but increases the customer experience. Maximum 1000
            order lines.
        reference (str): Internal reference to the refund that is also included in
            the settlement files. Max length is 255 characters.
        refund_id (str): The refund id. Generated when the refund is created.
        refunded_amount (int): Refunded amount in minor units.
        refunded_at (datetime): The time of the refund. ISO 8601.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "credit_invoice": "credit_invoice",
        "description": "description",
        "order_lines": "order_lines",
        "reference": "reference",
        "refund_id": "refund_id",
        "refunded_amount": "refunded_amount",
        "refunded_at": "refunded_at",
    }

    _optionals = [
        "credit_invoice",
        "description",
        "order_lines",
        "reference",
        "refund_id",
        "refunded_amount",
        "refunded_at",
    ]

    def __init__(
        self,
        credit_invoice=APIHelper.SKIP,
        description=APIHelper.SKIP,
        order_lines=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        refund_id=APIHelper.SKIP,
        refunded_amount=APIHelper.SKIP,
        refunded_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Refund instance."""
        # Initialize members of the class
        if credit_invoice is not APIHelper.SKIP:
            self.credit_invoice = credit_invoice
        if description is not APIHelper.SKIP:
            self.description = description
        if order_lines is not APIHelper.SKIP:
            self.order_lines = order_lines
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if refund_id is not APIHelper.SKIP:
            self.refund_id = refund_id
        if refunded_amount is not APIHelper.SKIP:
            self.refunded_amount = refunded_amount
        if refunded_at is not APIHelper.SKIP:
            self.refunded_at =\
                 APIHelper.apply_datetime_converter(
                refunded_at, APIHelper.RFC3339DateTime)\
                 if refunded_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        credit_invoice =\
            dictionary.get("credit_invoice")\
            if "credit_invoice" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        order_lines = None
        if dictionary.get("order_lines") is not None:
            order_lines = [
                OrderLine.from_dictionary(x)
                    for x in dictionary.get("order_lines")
            ]
        else:
            order_lines = APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        refund_id =\
            dictionary.get("refund_id")\
            if dictionary.get("refund_id")\
                else APIHelper.SKIP
        refunded_amount =\
            dictionary.get("refunded_amount")\
            if dictionary.get("refunded_amount")\
                else APIHelper.SKIP
        refunded_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("refunded_at")).datetime\
            if dictionary.get("refunded_at") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(credit_invoice,
                   description,
                   order_lines,
                   reference,
                   refund_id,
                   refunded_amount,
                   refunded_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _credit_invoice=(
            self.credit_invoice
            if hasattr(self, "credit_invoice")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _refund_id=(
            self.refund_id
            if hasattr(self, "refund_id")
            else None
        )
        _refunded_amount=(
            self.refunded_amount
            if hasattr(self, "refunded_amount")
            else None
        )
        _refunded_at=(
            self.refunded_at
            if hasattr(self, "refunded_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"credit_invoice={_credit_invoice!r}, "
            f"description={_description!r}, "
            f"order_lines={_order_lines!r}, "
            f"reference={_reference!r}, "
            f"refund_id={_refund_id!r}, "
            f"refunded_amount={_refunded_amount!r}, "
            f"refunded_at={_refunded_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _credit_invoice=(
            self.credit_invoice
            if hasattr(self, "credit_invoice")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _order_lines=(
            self.order_lines
            if hasattr(self, "order_lines")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _refund_id=(
            self.refund_id
            if hasattr(self, "refund_id")
            else None
        )
        _refunded_amount=(
            self.refunded_amount
            if hasattr(self, "refunded_amount")
            else None
        )
        _refunded_at=(
            self.refunded_at
            if hasattr(self, "refunded_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"credit_invoice={_credit_invoice!s}, "
            f"description={_description!s}, "
            f"order_lines={_order_lines!s}, "
            f"reference={_reference!s}, "
            f"refund_id={_refund_id!s}, "
            f"refunded_amount={_refunded_amount!s}, "
            f"refunded_at={_refunded_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
