"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.payment_dispute_representment_request import (
    PaymentDisputeRepresentmentRequest,
)
from klarna.models.payment_dispute_representment_state import (
    PaymentDisputeRepresentmentState,
)


class Representment(object):
    """Implementation of the 'Representment' model.

    The representment case details if the dispute has transitioned to representment
    state.

    Attributes:
        state (PaymentDisputeRepresentmentState): The current state of the Dispute
            Evidence Request.  * `EVIDENCE_REQUESTED` - Partner can reply to the
            request. * `EVIDENCE_RECEIVED` - Evidence is being reviewed by Klarna,
            it's not possible to reply to the request. * `EVIDENCE_REQUEST_EXPIRED` -
            Request time expired, it's not possible to reply to the request. The
            dispute will result in outcome LOST if partner does not respond before
            the deadline. * `EVIDENCE_WAIVED` - Partner accepted the dispute loss in
            INITIATED state using the accept-loss endpoint. No further action
            possible. * `REPRESENTMENT_AUTOMATICALLY_REJECTED` - Dispute
            representment automatically rejected because the dispute amount falls
            below the partner's configured threshold. Disputes below this threshold
            are automatically accepted as LOST. No further action possible.
        expires_at (datetime): Deadline date for a partner to accept or escalate to
            arbitration
        request (PaymentDisputeRepresentmentRequest): Request for information towards
            the associated partner
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "state": "state",
        "expires_at": "expires_at",
        "request": "request",
    }

    def __init__(
        self,
        state=None,
        expires_at=None,
        request=None,
        additional_properties=None):
        """Initialize a Representment instance."""
        # Initialize members of the class
        self.state = state
        self.expires_at =\
             APIHelper.apply_datetime_converter(
            expires_at, APIHelper.RFC3339DateTime)\
             if expires_at else None
        self.request = request

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else None
        expires_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expires_at")).datetime\
            if dictionary.get("expires_at") else None
        request =\
            PaymentDisputeRepresentmentRequest.from_dictionary(
                dictionary.get("request"))\
                if dictionary.get("request") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(state,
                   expires_at,
                   request,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.state,
                    type_callable=lambda value:
                        PaymentDisputeRepresentmentState.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.expires_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.request,
                    type_callable=lambda value:
                        PaymentDisputeRepresentmentRequest.validate(value),
                    is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("state"),
                type_callable=lambda value:
                    PaymentDisputeRepresentmentState.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("expires_at"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("request"),
                type_callable=lambda value:
                    PaymentDisputeRepresentmentRequest.validate(value),
                is_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _state=self.state
        _expires_at=self.expires_at
        _request=self.request
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"state={_state!r}, "
            f"expires_at={_expires_at!r}, "
            f"request={_request!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _state=self.state
        _expires_at=self.expires_at
        _request=self.request
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"state={_state!s}, "
            f"expires_at={_expires_at!s}, "
            f"request={_request!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
