"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.merchant_urls_v_1 import (
    MerchantUrlsV1,
)
from klarna.models.options_v_1 import OptionsV1


class SessionCreationRequestV1(object):
    """Implementation of the 'SessionCreationRequestV1' model.

    Attributes:
        merchant_urls (MerchantUrlsV1): The model property of type MerchantUrlsV1.
        options (OptionsV1): The model property of type OptionsV1.
        payment_session_url (str): URL of the KP Session or KCO Order to be hosted by
            the HPP Session
        profile_id (str): Profile id for default session options
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_session_url": "payment_session_url",
        "merchant_urls": "merchant_urls",
        "options": "options",
        "profile_id": "profile_id",
    }

    _optionals = [
        "merchant_urls",
        "options",
        "profile_id",
    ]

    def __init__(
        self,
        payment_session_url=None,
        merchant_urls=APIHelper.SKIP,
        options=APIHelper.SKIP,
        profile_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SessionCreationRequestV1 instance."""
        # Initialize members of the class
        if merchant_urls is not APIHelper.SKIP:
            self.merchant_urls = merchant_urls
        if options is not APIHelper.SKIP:
            self.options = options
        self.payment_session_url = payment_session_url
        if profile_id is not APIHelper.SKIP:
            self.profile_id = profile_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_session_url =\
            dictionary.get("payment_session_url")\
            if dictionary.get("payment_session_url")\
                else None
        merchant_urls =\
            MerchantUrlsV1.from_dictionary(
                dictionary.get("merchant_urls"))\
                if "merchant_urls" in dictionary.keys()\
                else APIHelper.SKIP
        options =\
            OptionsV1.from_dictionary(
                dictionary.get("options"))\
                if "options" in dictionary.keys()\
                else APIHelper.SKIP
        profile_id =\
            dictionary.get("profile_id")\
            if dictionary.get("profile_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(payment_session_url,
                   merchant_urls,
                   options,
                   profile_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_urls=(
            self.merchant_urls
            if hasattr(self, "merchant_urls")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _payment_session_url=self.payment_session_url
        _profile_id=(
            self.profile_id
            if hasattr(self, "profile_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_urls={_merchant_urls!r}, "
            f"options={_options!r}, "
            f"payment_session_url={_payment_session_url!r}, "
            f"profile_id={_profile_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_urls=(
            self.merchant_urls
            if hasattr(self, "merchant_urls")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _payment_session_url=self.payment_session_url
        _profile_id=(
            self.profile_id
            if hasattr(self, "profile_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_urls={_merchant_urls!s}, "
            f"options={_options!s}, "
            f"payment_session_url={_payment_session_url!s}, "
            f"profile_id={_profile_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
