"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.card import Card


class SettlementResponse(object):
    """Implementation of the 'settlement_response' model.

    Attributes:
        settlement_id (str): Unique settlement identifier.
        promise_id (str): Unique identifier for the promise associated to the
            settlement.
        order_id (str): Unique identifier for the order associated to the settlement.
        cards (List[Card]): An array of Card objects.
        created_at (str): Settlement creation datetime (ISO 8601).
        expires_at (str): Settlement expiration datetime (ISO 8601).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "settlement_id": "settlement_id",
        "promise_id": "promise_id",
        "order_id": "order_id",
        "cards": "cards",
        "created_at": "created_at",
        "expires_at": "expires_at",
    }

    _optionals = [
        "settlement_id",
        "promise_id",
        "order_id",
        "cards",
        "created_at",
        "expires_at",
    ]

    def __init__(
        self,
        settlement_id=APIHelper.SKIP,
        promise_id=APIHelper.SKIP,
        order_id=APIHelper.SKIP,
        cards=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        expires_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SettlementResponse instance."""
        # Initialize members of the class
        if settlement_id is not APIHelper.SKIP:
            self.settlement_id = settlement_id
        if promise_id is not APIHelper.SKIP:
            self.promise_id = promise_id
        if order_id is not APIHelper.SKIP:
            self.order_id = order_id
        if cards is not APIHelper.SKIP:
            self.cards = cards
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if expires_at is not APIHelper.SKIP:
            self.expires_at = expires_at

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        settlement_id =\
            dictionary.get("settlement_id")\
            if dictionary.get("settlement_id")\
                else APIHelper.SKIP
        promise_id =\
            dictionary.get("promise_id")\
            if dictionary.get("promise_id")\
                else APIHelper.SKIP
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else APIHelper.SKIP
        cards = None
        if dictionary.get("cards") is not None:
            cards = [
                Card.from_dictionary(x)
                    for x in dictionary.get("cards")
            ]
        else:
            cards = APIHelper.SKIP
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else APIHelper.SKIP
        expires_at =\
            dictionary.get("expires_at")\
            if dictionary.get("expires_at")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(settlement_id,
                   promise_id,
                   order_id,
                   cards,
                   created_at,
                   expires_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _settlement_id=(
            self.settlement_id
            if hasattr(self, "settlement_id")
            else None
        )
        _promise_id=(
            self.promise_id
            if hasattr(self, "promise_id")
            else None
        )
        _order_id=(
            self.order_id
            if hasattr(self, "order_id")
            else None
        )
        _cards=(
            self.cards
            if hasattr(self, "cards")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"settlement_id={_settlement_id!r}, "
            f"promise_id={_promise_id!r}, "
            f"order_id={_order_id!r}, "
            f"cards={_cards!r}, "
            f"created_at={_created_at!r}, "
            f"expires_at={_expires_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _settlement_id=(
            self.settlement_id
            if hasattr(self, "settlement_id")
            else None
        )
        _promise_id=(
            self.promise_id
            if hasattr(self, "promise_id")
            else None
        )
        _order_id=(
            self.order_id
            if hasattr(self, "order_id")
            else None
        )
        _cards=(
            self.cards
            if hasattr(self, "cards")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"settlement_id={_settlement_id!s}, "
            f"promise_id={_promise_id!s}, "
            f"order_id={_order_id!s}, "
            f"cards={_cards!s}, "
            f"created_at={_created_at!s}, "
            f"expires_at={_expires_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
