"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class SettlementRequest(object):
    """Implementation of the 'settlement_request' model.

    Attributes:
        promise_id (str): Unique identifier for the promise associated to the
            settlement.
        order_id (str): Unique identifier for the order associated to the settlement.
        key_id (str): Unique identifier for the public key to be used for encryption
            of the card data.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_id": "order_id",
        "key_id": "key_id",
        "promise_id": "promise_id",
    }

    _optionals = [
        "promise_id",
    ]

    def __init__(
        self,
        order_id=None,
        key_id=None,
        promise_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SettlementRequest instance."""
        # Initialize members of the class
        if promise_id is not APIHelper.SKIP:
            self.promise_id = promise_id
        self.order_id = order_id
        self.key_id = key_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else None
        key_id =\
            dictionary.get("key_id")\
            if dictionary.get("key_id")\
                else None
        promise_id =\
            dictionary.get("promise_id")\
            if dictionary.get("promise_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_id,
                   key_id,
                   promise_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _promise_id=(
            self.promise_id
            if hasattr(self, "promise_id")
            else None
        )
        _order_id=self.order_id
        _key_id=self.key_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"promise_id={_promise_id!r}, "
            f"order_id={_order_id!r}, "
            f"key_id={_key_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _promise_id=(
            self.promise_id
            if hasattr(self, "promise_id")
            else None
        )
        _order_id=self.order_id
        _key_id=self.key_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"promise_id={_promise_id!s}, "
            f"order_id={_order_id!s}, "
            f"key_id={_key_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
