"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class ShippingInfo(object):
    """Implementation of the 'shipping_info' model.

    Shipping information for this capture.

    Attributes:
        return_shipping_company (str): Identifier of the shipping company for the
            return shipment. The value should be a valid SHIPPING_COMPANY from the
            [Carrier
            list](https://docs.klarna.com/payments/after-payments/order-management/mor
            e-actions/klarna-carrier-partner-list/).
        return_tracking_number (str): Tracking number for the return shipment.
            Maximum 100 characters.
        return_tracking_uri (str): URL where the customer can track the return
            shipment. Maximum 1024 characters.
        shipping_company (str): Identifier of the shipping company. The value should
            be a valid SHIPPING_COMPANY from the [Carrier
            list](https://docs.klarna.com/payments/after-payments/order-management/mor
            e-actions/klarna-carrier-partner-list/).
        shipping_method (str): Shipping method. Allowed values matches
            (PickUpStore|Home|BoxReg|BoxUnreg|PickUpPoint|Own|Postal|DHLPackstation|Di
            gital|Undefined|PickUpWarehouse|ClickCollect|PalletDelivery)
        tracking_number (str): Tracking number for the shipment. Maximum 100
            characters.
        tracking_uri (str): URI where the customer can track their shipment. Maximum
            1024 characters.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "return_shipping_company": "return_shipping_company",
        "return_tracking_number": "return_tracking_number",
        "return_tracking_uri": "return_tracking_uri",
        "shipping_company": "shipping_company",
        "shipping_method": "shipping_method",
        "tracking_number": "tracking_number",
        "tracking_uri": "tracking_uri",
    }

    _optionals = [
        "return_shipping_company",
        "return_tracking_number",
        "return_tracking_uri",
        "shipping_company",
        "shipping_method",
        "tracking_number",
        "tracking_uri",
    ]

    def __init__(
        self,
        return_shipping_company=APIHelper.SKIP,
        return_tracking_number=APIHelper.SKIP,
        return_tracking_uri=APIHelper.SKIP,
        shipping_company=APIHelper.SKIP,
        shipping_method=APIHelper.SKIP,
        tracking_number=APIHelper.SKIP,
        tracking_uri=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ShippingInfo instance."""
        # Initialize members of the class
        if return_shipping_company is not APIHelper.SKIP:
            self.return_shipping_company = return_shipping_company
        if return_tracking_number is not APIHelper.SKIP:
            self.return_tracking_number = return_tracking_number
        if return_tracking_uri is not APIHelper.SKIP:
            self.return_tracking_uri = return_tracking_uri
        if shipping_company is not APIHelper.SKIP:
            self.shipping_company = shipping_company
        if shipping_method is not APIHelper.SKIP:
            self.shipping_method = shipping_method
        if tracking_number is not APIHelper.SKIP:
            self.tracking_number = tracking_number
        if tracking_uri is not APIHelper.SKIP:
            self.tracking_uri = tracking_uri

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        return_shipping_company =\
            dictionary.get("return_shipping_company")\
            if dictionary.get("return_shipping_company")\
                else APIHelper.SKIP
        return_tracking_number =\
            dictionary.get("return_tracking_number")\
            if dictionary.get("return_tracking_number")\
                else APIHelper.SKIP
        return_tracking_uri =\
            dictionary.get("return_tracking_uri")\
            if dictionary.get("return_tracking_uri")\
                else APIHelper.SKIP
        shipping_company =\
            dictionary.get("shipping_company")\
            if dictionary.get("shipping_company")\
                else APIHelper.SKIP
        shipping_method =\
            dictionary.get("shipping_method")\
            if dictionary.get("shipping_method")\
                else APIHelper.SKIP
        tracking_number =\
            dictionary.get("tracking_number")\
            if dictionary.get("tracking_number")\
                else APIHelper.SKIP
        tracking_uri =\
            dictionary.get("tracking_uri")\
            if dictionary.get("tracking_uri")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(return_shipping_company,
                   return_tracking_number,
                   return_tracking_uri,
                   shipping_company,
                   shipping_method,
                   tracking_number,
                   tracking_uri,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _return_shipping_company=(
            self.return_shipping_company
            if hasattr(self, "return_shipping_company")
            else None
        )
        _return_tracking_number=(
            self.return_tracking_number
            if hasattr(self, "return_tracking_number")
            else None
        )
        _return_tracking_uri=(
            self.return_tracking_uri
            if hasattr(self, "return_tracking_uri")
            else None
        )
        _shipping_company=(
            self.shipping_company
            if hasattr(self, "shipping_company")
            else None
        )
        _shipping_method=(
            self.shipping_method
            if hasattr(self, "shipping_method")
            else None
        )
        _tracking_number=(
            self.tracking_number
            if hasattr(self, "tracking_number")
            else None
        )
        _tracking_uri=(
            self.tracking_uri
            if hasattr(self, "tracking_uri")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"return_shipping_company={_return_shipping_company!r}, "
            f"return_tracking_number={_return_tracking_number!r}, "
            f"return_tracking_uri={_return_tracking_uri!r}, "
            f"shipping_company={_shipping_company!r}, "
            f"shipping_method={_shipping_method!r}, "
            f"tracking_number={_tracking_number!r}, "
            f"tracking_uri={_tracking_uri!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _return_shipping_company=(
            self.return_shipping_company
            if hasattr(self, "return_shipping_company")
            else None
        )
        _return_tracking_number=(
            self.return_tracking_number
            if hasattr(self, "return_tracking_number")
            else None
        )
        _return_tracking_uri=(
            self.return_tracking_uri
            if hasattr(self, "return_tracking_uri")
            else None
        )
        _shipping_company=(
            self.shipping_company
            if hasattr(self, "shipping_company")
            else None
        )
        _shipping_method=(
            self.shipping_method
            if hasattr(self, "shipping_method")
            else None
        )
        _tracking_number=(
            self.tracking_number
            if hasattr(self, "tracking_number")
            else None
        )
        _tracking_uri=(
            self.tracking_uri
            if hasattr(self, "tracking_uri")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"return_shipping_company={_return_shipping_company!s}, "
            f"return_tracking_number={_return_tracking_number!s}, "
            f"return_tracking_uri={_return_tracking_uri!s}, "
            f"shipping_company={_shipping_company!s}, "
            f"shipping_method={_shipping_method!s}, "
            f"tracking_number={_tracking_number!s}, "
            f"tracking_uri={_tracking_uri!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
