"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class SortBy(object):
    """Implementation of the 'sort_by' enum.

    Attributes:
        CREATED_AT: The enum member of type str.
        ENUM_CREATED_AT: The enum member of type str.
        CLOSED_AT: The enum member of type str.
        ENUM_CLOSED_AT: The enum member of type str.

    """

    CREATED_AT = "created_at"

    ENUM_CREATED_AT = "-created_at"

    CLOSED_AT = "closed_at"

    ENUM_CLOSED_AT = "-closed_at"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
