"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class State5(object):
    """Implementation of the 'State5' enum.

    The new state of the dispute after submitting the response. The dispute
    transitions to REPRESENTMENT state for Klarna review.

    Attributes:
        INITIATED: The enum member of type str.
        REPRESENTMENT: The enum member of type str.
        PRE_ARBITRATION: The enum member of type str.
        ARBITRATION: The enum member of type str.
        CLOSED: The enum member of type str.

    """

    _all_values = ["INITIATED", "REPRESENTMENT", "PRE_ARBITRATION", "ARBITRATION", "CLOSED"]
    INITIATED = "INITIATED"

    REPRESENTMENT = "REPRESENTMENT"

    PRE_ARBITRATION = "PRE_ARBITRATION"

    ARBITRATION = "ARBITRATION"

    CLOSED = "CLOSED"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
