"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.models.payment_dispute_partner_evidence import (
    PaymentDisputePartnerEvidence,
)


class StateContext1(object):
    """Implementation of the 'StateContext1' model.

    Additional context specific to the current dispute state. Required in all states,
    with different schemas depending on the state.

    Attributes:
        partner_evidence (PaymentDisputePartnerEvidence): Partner representment
            responses
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "partner_evidence": "partner_evidence",
    }

    def __init__(
        self,
        partner_evidence=None,
        additional_properties=None):
        """Initialize a StateContext1 instance."""
        # Initialize members of the class
        self.partner_evidence = partner_evidence

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        partner_evidence =\
            PaymentDisputePartnerEvidence.from_dictionary(
                dictionary.get("partner_evidence"))\
                if dictionary.get("partner_evidence") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(partner_evidence,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.partner_evidence,
                    type_callable=lambda value:
                        PaymentDisputePartnerEvidence.validate(value),
                    is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("partner_evidence"),
                type_callable=lambda value:
                    PaymentDisputePartnerEvidence.validate(value),
                is_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _partner_evidence=self.partner_evidence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"partner_evidence={_partner_evidence!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _partner_evidence=self.partner_evidence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"partner_evidence={_partner_evidence!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
