"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Subscription1(object):
    """Implementation of the 'subscription1' model.

    Attributes:
        name (str): The name of the subscription product
        interval (Interval): The cadence unit for this.
        interval_count (int): The number of intervals
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "interval": "interval",
        "interval_count": "interval_count",
    }

    def __init__(
        self,
        name=None,
        interval=None,
        interval_count=None,
        additional_properties=None):
        """Initialize a Subscription1 instance."""
        # Initialize members of the class
        self.name = name
        self.interval = interval
        self.interval_count = interval_count

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        interval =\
            dictionary.get("interval")\
            if dictionary.get("interval")\
                else None
        interval_count =\
            dictionary.get("interval_count")\
            if dictionary.get("interval_count")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   interval,
                   interval_count,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _interval=self.interval
        _interval_count=self.interval_count
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"interval={_interval!r}, "
            f"interval_count={_interval_count!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _interval=self.interval
        _interval_count=self.interval_count
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"interval={_interval!s}, "
            f"interval_count={_interval_count!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
