"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Timeslot(object):
    """Implementation of the 'Timeslot' model.

    The chosen timeslot of the selected shipping option

    Attributes:
        cutoff (str): Cutoff time for delivery
        end (str): End of the timeslot
        id (str): The timeslot id
        price (int): Price
        start (str): Start of the timeslot
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cutoff": "cutoff",
        "end": "end",
        "id": "id",
        "price": "price",
        "start": "start",
    }

    _optionals = [
        "cutoff",
        "end",
        "id",
        "price",
        "start",
    ]

    def __init__(
        self,
        cutoff=APIHelper.SKIP,
        end=APIHelper.SKIP,
        id=APIHelper.SKIP,
        price=APIHelper.SKIP,
        start=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Timeslot instance."""
        # Initialize members of the class
        if cutoff is not APIHelper.SKIP:
            self.cutoff = cutoff
        if end is not APIHelper.SKIP:
            self.end = end
        if id is not APIHelper.SKIP:
            self.id = id
        if price is not APIHelper.SKIP:
            self.price = price
        if start is not APIHelper.SKIP:
            self.start = start

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cutoff =\
            dictionary.get("cutoff")\
            if dictionary.get("cutoff")\
                else APIHelper.SKIP
        end =\
            dictionary.get("end")\
            if dictionary.get("end")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else APIHelper.SKIP
        start =\
            dictionary.get("start")\
            if dictionary.get("start")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(cutoff,
                   end,
                   id,
                   price,
                   start,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cutoff=(
            self.cutoff
            if hasattr(self, "cutoff")
            else None
        )
        _end=(
            self.end
            if hasattr(self, "end")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _start=(
            self.start
            if hasattr(self, "start")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cutoff={_cutoff!r}, "
            f"end={_end!r}, "
            f"id={_id!r}, "
            f"price={_price!r}, "
            f"start={_start!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cutoff=(
            self.cutoff
            if hasattr(self, "cutoff")
            else None
        )
        _end=(
            self.end
            if hasattr(self, "end")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _start=(
            self.start
            if hasattr(self, "start")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cutoff={_cutoff!s}, "
            f"end={_end!s}, "
            f"id={_id!s}, "
            f"price={_price!s}, "
            f"start={_start!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
