"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class Transaction(object):
    """Implementation of the 'Transaction' model.

    Attributes:
        amount (int): Total amount of the specific transaction, in minor units
        capture_id (str): Each capture on an order is assigned a unique identifier,
            referred to as the capture_id, which is provided exclusively for sale and
            fee transactions. In instances of partial shipments, an order may undergo
            multiple captures, each of which is reflected as a separate transaction
            with its own unique capture_id. It's important to note that for certain
            transaction types such as RETURNS and REVERSALS, where captures do not
            exist, the API will return empty strings for the capture_ID field.
        merchant_reference_1 (str): Merchant assigned reference, typically a
            reference to an order management system id
        sale_date (datetime): ISO 8601 formatted date-time string
        mtype (Type2): The type of transaction.
        capture_date (datetime): ISO 8601 formatted date-time string
        payment_reference (str): Reference to the specific payout the transaction is
            part of, if available.
        order_id (uuid|str): The Klarna assigned order id reference
        payout (str): Link to the payout that this transaction is part of
        refund_id (str): The Klarna assigned id reference of a specific refund
        short_order_id (str): The Klarna assigned short order id reference
        merchant_reference_2 (str): Merchant assigned reference, typically a
            reference to an order management system id
        currency_code (str): ISO 4217 Currency Code. Like USD, EUR, AUD or GBP.
        purchase_country (str): ISO Alpha-2 Country Code
        vat_rate (int): VAT (Value added tax) rate on Klarna fees
        vat_amount (int): VAT (Value added tax) amount on Klarna fees, in minor units
        shipping_country (str): ISO Alpha-2 Country Code
        initial_payment_method_type (str): Payment method the consumer chose during
            checkout
        initial_number_of_installments (int): Number of installments the consumer
            chose during checkout in case of installment payments
        initial_payment_method_monthly_downpayments (int): Number of monthly
            downpayments that were chosen during the checkout in case of installment
            payments.
        merchant_capture_reference (str): Your internal reference to the capture,
            that has been submitted during capturing an order via API
        merchant_refund_reference (str): Your internal reference to the refund, that
            has been submitted during refunding an order via API
        detailed_type (DetailedType): Detailed description of the transaction type
        tax_in_currency_of_registration_country (int): The tax amount on the
            respective fee, converted into the currency of your registration country.
            In case you are a German merchant selling in another currency then EUR or
            a Swedish merchant selling in another currency then SEK, we convert the
            VAT amount on the Klarna fees into the currency of the country you are
            registered in, based on the exchange rate of the capture date.
        currency_code_of_registration_country (str): ISO 4217 Currency Code of the
            country you are registered in.
        klarna_comment (str): Any additional information necessary to provide more
            context about the transaction.
        reversal_reference (str): Unique internal identifier, known as DisputeKRN,
            assigned to each dispute by Klarna. This identifier includes a dispute
            category and a numeric code, enabling efficient tracking and management
            of the dispute's status.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "sale_date": "sale_date",
        "mtype": "type",
        "capture_date": "capture_date",
        "order_id": "order_id",
        "currency_code": "currency_code",
        "purchase_country": "purchase_country",
        "capture_id": "capture_id",
        "merchant_reference_1": "merchant_reference1",
        "payment_reference": "payment_reference",
        "payout": "payout",
        "refund_id": "refund_id",
        "short_order_id": "short_order_id",
        "merchant_reference_2": "merchant_reference2",
        "vat_rate": "vat_rate",
        "vat_amount": "vat_amount",
        "shipping_country": "shipping_country",
        "initial_payment_method_type": "initial_payment_method_type",
        "initial_number_of_installments": "initial_number_of_installments",
        "initial_payment_method_monthly_downpayments":
            "initial_payment_method_monthly_downpayments",
        "merchant_capture_reference": "merchant_capture_reference",
        "merchant_refund_reference": "merchant_refund_reference",
        "detailed_type": "detailed_type",
        "tax_in_currency_of_registration_country":
            "tax_in_currency_of_registration_country",
        "currency_code_of_registration_country":
            "currency_code_of_registration_country",
        "klarna_comment": "klarna_comment",
        "reversal_reference": "reversal_reference",
    }

    _optionals = [
        "capture_id",
        "merchant_reference_1",
        "payment_reference",
        "payout",
        "refund_id",
        "short_order_id",
        "merchant_reference_2",
        "vat_rate",
        "vat_amount",
        "shipping_country",
        "initial_payment_method_type",
        "initial_number_of_installments",
        "initial_payment_method_monthly_downpayments",
        "merchant_capture_reference",
        "merchant_refund_reference",
        "detailed_type",
        "tax_in_currency_of_registration_country",
        "currency_code_of_registration_country",
        "klarna_comment",
        "reversal_reference",
    ]

    def __init__(
        self,
        amount=None,
        sale_date=None,
        mtype=None,
        capture_date=None,
        order_id=None,
        currency_code=None,
        purchase_country=None,
        capture_id=APIHelper.SKIP,
        merchant_reference_1=APIHelper.SKIP,
        payment_reference=APIHelper.SKIP,
        payout=APIHelper.SKIP,
        refund_id=APIHelper.SKIP,
        short_order_id=APIHelper.SKIP,
        merchant_reference_2=APIHelper.SKIP,
        vat_rate=APIHelper.SKIP,
        vat_amount=APIHelper.SKIP,
        shipping_country=APIHelper.SKIP,
        initial_payment_method_type=APIHelper.SKIP,
        initial_number_of_installments=APIHelper.SKIP,
        initial_payment_method_monthly_downpayments=APIHelper.SKIP,
        merchant_capture_reference=APIHelper.SKIP,
        merchant_refund_reference=APIHelper.SKIP,
        detailed_type=APIHelper.SKIP,
        tax_in_currency_of_registration_country=APIHelper.SKIP,
        currency_code_of_registration_country=APIHelper.SKIP,
        klarna_comment=APIHelper.SKIP,
        reversal_reference=APIHelper.SKIP):
        """Initialize a Transaction instance."""
        # Initialize members of the class
        self.amount = amount
        if capture_id is not APIHelper.SKIP:
            self.capture_id = capture_id
        if merchant_reference_1 is not APIHelper.SKIP:
            self.merchant_reference_1 = merchant_reference_1
        self.sale_date =\
             APIHelper.apply_datetime_converter(
            sale_date, APIHelper.RFC3339DateTime)\
             if sale_date else None
        self.mtype = mtype
        self.capture_date =\
             APIHelper.apply_datetime_converter(
            capture_date, APIHelper.RFC3339DateTime)\
             if capture_date else None
        if payment_reference is not APIHelper.SKIP:
            self.payment_reference = payment_reference
        self.order_id = order_id
        if payout is not APIHelper.SKIP:
            self.payout = payout
        if refund_id is not APIHelper.SKIP:
            self.refund_id = refund_id
        if short_order_id is not APIHelper.SKIP:
            self.short_order_id = short_order_id
        if merchant_reference_2 is not APIHelper.SKIP:
            self.merchant_reference_2 = merchant_reference_2
        self.currency_code = currency_code
        self.purchase_country = purchase_country
        if vat_rate is not APIHelper.SKIP:
            self.vat_rate = vat_rate
        if vat_amount is not APIHelper.SKIP:
            self.vat_amount = vat_amount
        if shipping_country is not APIHelper.SKIP:
            self.shipping_country = shipping_country
        if initial_payment_method_type is not APIHelper.SKIP:
            self.initial_payment_method_type = initial_payment_method_type
        if initial_number_of_installments is not APIHelper.SKIP:
            self.initial_number_of_installments = initial_number_of_installments
        if initial_payment_method_monthly_downpayments is not APIHelper.SKIP:
            self.initial_payment_method_monthly_downpayments =\
                 initial_payment_method_monthly_downpayments
        if merchant_capture_reference is not APIHelper.SKIP:
            self.merchant_capture_reference = merchant_capture_reference
        if merchant_refund_reference is not APIHelper.SKIP:
            self.merchant_refund_reference = merchant_refund_reference
        if detailed_type is not APIHelper.SKIP:
            self.detailed_type = detailed_type
        if tax_in_currency_of_registration_country is not APIHelper.SKIP:
            self.tax_in_currency_of_registration_country =\
                 tax_in_currency_of_registration_country
        if currency_code_of_registration_country is not APIHelper.SKIP:
            self.currency_code_of_registration_country =\
                 currency_code_of_registration_country
        if klarna_comment is not APIHelper.SKIP:
            self.klarna_comment = klarna_comment
        if reversal_reference is not APIHelper.SKIP:
            self.reversal_reference = reversal_reference

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        sale_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("sale_date")).datetime\
            if dictionary.get("sale_date") else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        capture_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("capture_date")).datetime\
            if dictionary.get("capture_date") else None
        order_id =\
            dictionary.get("order_id")\
            if dictionary.get("order_id")\
                else None
        currency_code =\
            dictionary.get("currency_code")\
            if dictionary.get("currency_code")\
                else None
        purchase_country =\
            dictionary.get("purchase_country")\
            if dictionary.get("purchase_country")\
                else None
        capture_id =\
            dictionary.get("capture_id")\
            if dictionary.get("capture_id")\
                else APIHelper.SKIP
        merchant_reference_1 =\
            dictionary.get("merchant_reference1")\
            if dictionary.get("merchant_reference1")\
                else APIHelper.SKIP
        payment_reference =\
            dictionary.get("payment_reference")\
            if dictionary.get("payment_reference")\
                else APIHelper.SKIP
        payout =\
            dictionary.get("payout")\
            if dictionary.get("payout")\
                else APIHelper.SKIP
        refund_id =\
            dictionary.get("refund_id")\
            if dictionary.get("refund_id")\
                else APIHelper.SKIP
        short_order_id =\
            dictionary.get("short_order_id")\
            if dictionary.get("short_order_id")\
                else APIHelper.SKIP
        merchant_reference_2 =\
            dictionary.get("merchant_reference2")\
            if dictionary.get("merchant_reference2")\
                else APIHelper.SKIP
        vat_rate =\
            dictionary.get("vat_rate")\
            if dictionary.get("vat_rate")\
                else APIHelper.SKIP
        vat_amount =\
            dictionary.get("vat_amount")\
            if dictionary.get("vat_amount")\
                else APIHelper.SKIP
        shipping_country =\
            dictionary.get("shipping_country")\
            if dictionary.get("shipping_country")\
                else APIHelper.SKIP
        initial_payment_method_type =\
            dictionary.get("initial_payment_method_type")\
            if dictionary.get("initial_payment_method_type")\
                else APIHelper.SKIP
        initial_number_of_installments =\
            dictionary.get("initial_number_of_installments")\
            if dictionary.get("initial_number_of_installments")\
                else APIHelper.SKIP
        initial_payment_method_monthly_downpayments =\
            dictionary.get("initial_payment_method_monthly_downpayments")\
            if dictionary.get("initial_payment_method_monthly_downpayments")\
                else APIHelper.SKIP
        merchant_capture_reference =\
            dictionary.get("merchant_capture_reference")\
            if dictionary.get("merchant_capture_reference")\
                else APIHelper.SKIP
        merchant_refund_reference =\
            dictionary.get("merchant_refund_reference")\
            if dictionary.get("merchant_refund_reference")\
                else APIHelper.SKIP
        detailed_type =\
            dictionary.get("detailed_type")\
            if dictionary.get("detailed_type")\
                else APIHelper.SKIP
        tax_in_currency_of_registration_country =\
            dictionary.get("tax_in_currency_of_registration_country")\
            if dictionary.get("tax_in_currency_of_registration_country")\
                else APIHelper.SKIP
        currency_code_of_registration_country =\
            dictionary.get("currency_code_of_registration_country")\
            if dictionary.get("currency_code_of_registration_country")\
                else APIHelper.SKIP
        klarna_comment =\
            dictionary.get("klarna_comment")\
            if dictionary.get("klarna_comment")\
                else APIHelper.SKIP
        reversal_reference =\
            dictionary.get("reversal_reference")\
            if dictionary.get("reversal_reference")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(amount,
                   sale_date,
                   mtype,
                   capture_date,
                   order_id,
                   currency_code,
                   purchase_country,
                   capture_id,
                   merchant_reference_1,
                   payment_reference,
                   payout,
                   refund_id,
                   short_order_id,
                   merchant_reference_2,
                   vat_rate,
                   vat_amount,
                   shipping_country,
                   initial_payment_method_type,
                   initial_number_of_installments,
                   initial_payment_method_monthly_downpayments,
                   merchant_capture_reference,
                   merchant_refund_reference,
                   detailed_type,
                   tax_in_currency_of_registration_country,
                   currency_code_of_registration_country,
                   klarna_comment,
                   reversal_reference)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=self.amount
        _capture_id=(
            self.capture_id
            if hasattr(self, "capture_id")
            else None
        )
        _merchant_reference_1=(
            self.merchant_reference_1
            if hasattr(self, "merchant_reference_1")
            else None
        )
        _sale_date=self.sale_date
        _mtype=self.mtype
        _capture_date=self.capture_date
        _payment_reference=(
            self.payment_reference
            if hasattr(self, "payment_reference")
            else None
        )
        _order_id=self.order_id
        _payout=(
            self.payout
            if hasattr(self, "payout")
            else None
        )
        _refund_id=(
            self.refund_id
            if hasattr(self, "refund_id")
            else None
        )
        _short_order_id=(
            self.short_order_id
            if hasattr(self, "short_order_id")
            else None
        )
        _merchant_reference_2=(
            self.merchant_reference_2
            if hasattr(self, "merchant_reference_2")
            else None
        )
        _currency_code=self.currency_code
        _purchase_country=self.purchase_country
        _vat_rate=(
            self.vat_rate
            if hasattr(self, "vat_rate")
            else None
        )
        _vat_amount=(
            self.vat_amount
            if hasattr(self, "vat_amount")
            else None
        )
        _shipping_country=(
            self.shipping_country
            if hasattr(self, "shipping_country")
            else None
        )
        _initial_payment_method_type=(
            self.initial_payment_method_type
            if hasattr(self, "initial_payment_method_type")
            else None
        )
        _initial_number_of_installments=(
            self.initial_number_of_installments
            if hasattr(self, "initial_number_of_installments")
            else None
        )
        _initial_payment_method_monthly_downpayments=(
            self.initial_payment_method_monthly_downpayments
            if hasattr(self, "initial_payment_method_monthly_downpayments")
            else None
        )
        _merchant_capture_reference=(
            self.merchant_capture_reference
            if hasattr(self, "merchant_capture_reference")
            else None
        )
        _merchant_refund_reference=(
            self.merchant_refund_reference
            if hasattr(self, "merchant_refund_reference")
            else None
        )
        _detailed_type=(
            self.detailed_type
            if hasattr(self, "detailed_type")
            else None
        )
        _tax_in_currency_of_registration_country=(
            self.tax_in_currency_of_registration_country
            if hasattr(self, "tax_in_currency_of_registration_country")
            else None
        )
        _currency_code_of_registration_country=(
            self.currency_code_of_registration_country
            if hasattr(self, "currency_code_of_registration_country")
            else None
        )
        _klarna_comment=(
            self.klarna_comment
            if hasattr(self, "klarna_comment")
            else None
        )
        _reversal_reference=(
            self.reversal_reference
            if hasattr(self, "reversal_reference")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"capture_id={_capture_id!r}, "
            f"merchant_reference_1={_merchant_reference_1!r}, "
            f"sale_date={_sale_date!r}, "
            f"mtype={_mtype!r}, "
            f"capture_date={_capture_date!r}, "
            f"payment_reference={_payment_reference!r}, "
            f"order_id={_order_id!r}, "
            f"payout={_payout!r}, "
            f"refund_id={_refund_id!r}, "
            f"short_order_id={_short_order_id!r}, "
            f"merchant_reference_2={_merchant_reference_2!r}, "
            f"currency_code={_currency_code!r}, "
            f"purchase_country={_purchase_country!r}, "
            f"vat_rate={_vat_rate!r}, "
            f"vat_amount={_vat_amount!r}, "
            f"shipping_country={_shipping_country!r}, "
            f"initial_payment_method_type={_initial_payment_method_type!r}, "
            f"initial_number_of_installments={_initial_number_of_installments!r}, "
            f"initial_payment_method_monthly_downpayments={_initial_payment_method_monthly_downpayments!r}, "
            f"merchant_capture_reference={_merchant_capture_reference!r}, "
            f"merchant_refund_reference={_merchant_refund_reference!r}, "
            f"detailed_type={_detailed_type!r}, "
            f"tax_in_currency_of_registration_country={_tax_in_currency_of_registration_country!r}, "
            f"currency_code_of_registration_country={_currency_code_of_registration_country!r}, "
            f"klarna_comment={_klarna_comment!r}, "
            f"reversal_reference={_reversal_reference!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=self.amount
        _capture_id=(
            self.capture_id
            if hasattr(self, "capture_id")
            else None
        )
        _merchant_reference_1=(
            self.merchant_reference_1
            if hasattr(self, "merchant_reference_1")
            else None
        )
        _sale_date=self.sale_date
        _mtype=self.mtype
        _capture_date=self.capture_date
        _payment_reference=(
            self.payment_reference
            if hasattr(self, "payment_reference")
            else None
        )
        _order_id=self.order_id
        _payout=(
            self.payout
            if hasattr(self, "payout")
            else None
        )
        _refund_id=(
            self.refund_id
            if hasattr(self, "refund_id")
            else None
        )
        _short_order_id=(
            self.short_order_id
            if hasattr(self, "short_order_id")
            else None
        )
        _merchant_reference_2=(
            self.merchant_reference_2
            if hasattr(self, "merchant_reference_2")
            else None
        )
        _currency_code=self.currency_code
        _purchase_country=self.purchase_country
        _vat_rate=(
            self.vat_rate
            if hasattr(self, "vat_rate")
            else None
        )
        _vat_amount=(
            self.vat_amount
            if hasattr(self, "vat_amount")
            else None
        )
        _shipping_country=(
            self.shipping_country
            if hasattr(self, "shipping_country")
            else None
        )
        _initial_payment_method_type=(
            self.initial_payment_method_type
            if hasattr(self, "initial_payment_method_type")
            else None
        )
        _initial_number_of_installments=(
            self.initial_number_of_installments
            if hasattr(self, "initial_number_of_installments")
            else None
        )
        _initial_payment_method_monthly_downpayments=(
            self.initial_payment_method_monthly_downpayments
            if hasattr(self, "initial_payment_method_monthly_downpayments")
            else None
        )
        _merchant_capture_reference=(
            self.merchant_capture_reference
            if hasattr(self, "merchant_capture_reference")
            else None
        )
        _merchant_refund_reference=(
            self.merchant_refund_reference
            if hasattr(self, "merchant_refund_reference")
            else None
        )
        _detailed_type=(
            self.detailed_type
            if hasattr(self, "detailed_type")
            else None
        )
        _tax_in_currency_of_registration_country=(
            self.tax_in_currency_of_registration_country
            if hasattr(self, "tax_in_currency_of_registration_country")
            else None
        )
        _currency_code_of_registration_country=(
            self.currency_code_of_registration_country
            if hasattr(self, "currency_code_of_registration_country")
            else None
        )
        _klarna_comment=(
            self.klarna_comment
            if hasattr(self, "klarna_comment")
            else None
        )
        _reversal_reference=(
            self.reversal_reference
            if hasattr(self, "reversal_reference")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"capture_id={_capture_id!s}, "
            f"merchant_reference_1={_merchant_reference_1!s}, "
            f"sale_date={_sale_date!s}, "
            f"mtype={_mtype!s}, "
            f"capture_date={_capture_date!s}, "
            f"payment_reference={_payment_reference!s}, "
            f"order_id={_order_id!s}, "
            f"payout={_payout!s}, "
            f"refund_id={_refund_id!s}, "
            f"short_order_id={_short_order_id!s}, "
            f"merchant_reference_2={_merchant_reference_2!s}, "
            f"currency_code={_currency_code!s}, "
            f"purchase_country={_purchase_country!s}, "
            f"vat_rate={_vat_rate!s}, "
            f"vat_amount={_vat_amount!s}, "
            f"shipping_country={_shipping_country!s}, "
            f"initial_payment_method_type={_initial_payment_method_type!s}, "
            f"initial_number_of_installments={_initial_number_of_installments!s}, "
            f"initial_payment_method_monthly_downpayments={_initial_payment_method_monthly_downpayments!s}, "
            f"merchant_capture_reference={_merchant_capture_reference!s}, "
            f"merchant_refund_reference={_merchant_refund_reference!s}, "
            f"detailed_type={_detailed_type!s}, "
            f"tax_in_currency_of_registration_country={_tax_in_currency_of_registration_country!s}, "
            f"currency_code_of_registration_country={_currency_code_of_registration_country!s}, "
            f"klarna_comment={_klarna_comment!s}, "
            f"reversal_reference={_reversal_reference!s}, "
            f")"
        )
