"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type2(object):
    """Implementation of the 'Type2' enum.

    The type of transaction.

    Attributes:
        COMMISSION: The enum member of type str.
        SALE: The enum member of type str.
        REVERSAL: The enum member of type str.
        RETURN: The enum member of type str.
        TAX: The enum member of type str.
        FEE: The enum member of type str.
        FEE_REFUND: The enum member of type str.
        CORRECTION: The enum member of type str.
        REVERSAL_MERCHANT_PROTECTION: The enum member of type str.
        CHARGE: The enum member of type str.
        CREDIT: The enum member of type str.
        HOLDBACK: The enum member of type str.
        RELEASE: The enum member of type str.

    """

    COMMISSION = "COMMISSION"

    SALE = "SALE"

    REVERSAL = "REVERSAL"

    RETURN = "RETURN"

    TAX = "TAX"

    FEE = "FEE"

    FEE_REFUND = "FEE_REFUND"

    CORRECTION = "CORRECTION"

    REVERSAL_MERCHANT_PROTECTION = "REVERSAL_MERCHANT_PROTECTION"

    CHARGE = "CHARGE"

    CREDIT = "CREDIT"

    HOLDBACK = "HOLDBACK"

    RELEASE = "RELEASE"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
