"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper


class UpdateMerchantReferences(object):
    """Implementation of the 'UpdateMerchantReferences' model.

    Attributes:
        merchant_reference_1 (str): New merchant reference 1. Old reference will be
            overwritten if this field is present.
        merchant_reference_2 (str): New merchant reference 2. Old reference will be
            overwritten if this field is present.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_reference_1": "merchant_reference1",
        "merchant_reference_2": "merchant_reference2",
    }

    _optionals = [
        "merchant_reference_1",
        "merchant_reference_2",
    ]

    def __init__(
        self,
        merchant_reference_1=APIHelper.SKIP,
        merchant_reference_2=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UpdateMerchantReferences instance."""
        # Initialize members of the class
        if merchant_reference_1 is not APIHelper.SKIP:
            self.merchant_reference_1 = merchant_reference_1
        if merchant_reference_2 is not APIHelper.SKIP:
            self.merchant_reference_2 = merchant_reference_2

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_reference_1 =\
            dictionary.get("merchant_reference1")\
            if dictionary.get("merchant_reference1")\
                else APIHelper.SKIP
        merchant_reference_2 =\
            dictionary.get("merchant_reference2")\
            if dictionary.get("merchant_reference2")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(merchant_reference_1,
                   merchant_reference_2,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_reference_1=(
            self.merchant_reference_1
            if hasattr(self, "merchant_reference_1")
            else None
        )
        _merchant_reference_2=(
            self.merchant_reference_2
            if hasattr(self, "merchant_reference_2")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_reference_1={_merchant_reference_1!r}, "
            f"merchant_reference_2={_merchant_reference_2!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_reference_1=(
            self.merchant_reference_1
            if hasattr(self, "merchant_reference_1")
            else None
        )
        _merchant_reference_2=(
            self.merchant_reference_2
            if hasattr(self, "merchant_reference_2")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_reference_1={_merchant_reference_1!s}, "
            f"merchant_reference_2={_merchant_reference_2!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
