
"""
klarna

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: E501
from __future__ import annotations

from typing import (
    Callable,
    ClassVar,
)

from apimatic_core.types.union_types.any_of import (
    AnyOf,
)
from apimatic_core.types.union_types.leaf_type import (
    LeafType,
)
from apimatic_core.types.union_types.one_of import (
    OneOf,
)
from apimatic_core.types.union_types.union_type_context import (
    UnionTypeContext as Context,
)

from klarna.models.payment_dispute_body_arbitration import (
    PaymentDisputeBodyArbitration,
)
from klarna.models.payment_dispute_body_closed import (
    PaymentDisputeBodyClosed,
)
from klarna.models.payment_dispute_body_dispute_initiated import (
    PaymentDisputeBodyDisputeInitiated,
)
from klarna.models.payment_dispute_body_pre_arbitration import (
    PaymentDisputeBodyPreArbitration,
)
from klarna.models.payment_dispute_body_representment import (
    PaymentDisputeBodyRepresentment,
)
from klarna.models.payment_dispute_flow_dispute_window_extension_exceptions import (
    PaymentDisputeFlowDisputeWindowExtensionExceptions,
)
from klarna.models.payment_dispute_flow_immediate_dispute_resolution_exceptions import (
    PaymentDisputeFlowImmediateDisputeResolutionExceptions,
)
from klarna.models.payment_dispute_state_change import (
    PaymentDisputeStateChange,
)
from klarna.models.payment_dispute_state_change_arbitration import (
    PaymentDisputeStateChangeArbitration,
)
from klarna.models.payment_dispute_state_change_closed import (
    PaymentDisputeStateChangeClosed,
)
from klarna.models.payment_dispute_state_change_initiated import (
    PaymentDisputeStateChangeInitiated,
)
from klarna.models.payment_dispute_state_change_pre_arbitration import (
    PaymentDisputeStateChangePreArbitration,
)
from klarna.models.payment_dispute_state_change_representment import (
    PaymentDisputeStateChangeRepresentment,
)
from klarna.models.payment_dispute_updated import (
    PaymentDisputeUpdated,
)


class UnionTypeLookUp:
    """
    Provides lookup and factory methods for predefined union type templates.
    This class stores a mapping of template names to callables that construct
    union type instances. These templates are used to describe compatible
    data shapes by combining primitive or model-based types into a single
    resolved representation at runtime.

    Attributes:
        _templates (dict): A mapping of template names to factory callables
        that create configured union types.

    """

    _templates: ClassVar[dict[str, Callable]] = {
        "PaymentDisputeBody": lambda: OneOf(
            [
                LeafType(PaymentDisputeBodyDisputeInitiated,
                         Context.create(
                             discriminator_value="INITIATED",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyRepresentment,
                         Context.create(
                             discriminator_value="REPRESENTMENT",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyPreArbitration,
                         Context.create(
                             discriminator_value="PRE_ARBITRATION",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyArbitration,
                         Context.create(
                             discriminator_value="ARBITRATION",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyClosed,
                         Context.create(
                             discriminator_value="CLOSED",
                             discriminator="state",
                         )),
            ],
        ),
        "PaymentDisputeBody2": lambda: OneOf(
            [
                LeafType(PaymentDisputeBodyDisputeInitiated,
                         Context.create(
                             discriminator_value="INITIATED",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyRepresentment,
                         Context.create(
                             discriminator_value="REPRESENTMENT",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyPreArbitration,
                         Context.create(
                             discriminator_value="PRE_ARBITRATION",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyArbitration,
                         Context.create(
                             discriminator_value="ARBITRATION",
                             discriminator="state",
                         )),
                LeafType(PaymentDisputeBodyClosed,
                         Context.create(
                             discriminator_value="CLOSED",
                             discriminator="state",
                         )),
            ],
            Context.create(
               is_array=True,
            ),
        ),
        "PaymentDisputeStateChangePayload": lambda: AnyOf(
            [
                LeafType(PaymentDisputeStateChangeInitiated),
                LeafType(PaymentDisputeStateChangeRepresentment),
                LeafType(PaymentDisputeStateChangePreArbitration),
                LeafType(PaymentDisputeStateChangeArbitration),
                LeafType(PaymentDisputeStateChangeClosed),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "PaymentDisputeFlowExceptions": lambda: OneOf(
            [
                LeafType(PaymentDisputeFlowDisputeWindowExtensionExceptions,
                         Context.create(
                             discriminator_value="DISPUTE_WINDOW_EXTENSION",
                             discriminator="exception_type",
                         )),
                LeafType(PaymentDisputeFlowImmediateDisputeResolutionExceptions,
                         Context.create(
                             discriminator_value="IMMEDIATE_DISPUTE_RESOLUTION",
                             discriminator="exception_type",
                         )),
            ],
            Context.create(
               is_array=True,
               is_optional=True,
            ),
        ),
        "Callbacks": lambda: OneOf(
            [
                LeafType(PaymentDisputeStateChange),
                LeafType(PaymentDisputeUpdated),
            ],
        ),
    }

    @staticmethod
    def get(name):
        """
        Retrieve and construct a union type template by name.

        Args:
            name (str): The key identifying the template to resolve.

        Returns:
            Any: A new instance of the union type defined for the given name.

        Raises:
            KeyError: If no template exists for the specified name.

        """
        return UnionTypeLookUp._templates[name]()
