"""
 klarna

 This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""
from __future__ import annotations

from typing import Union

from klarna.api_helper import APIHelper
from klarna.events.unknown_event import UnknownEvent
from klarna.http.request import Request
from klarna.models.payment_dispute_state_change import (
    PaymentDisputeStateChange,
)
from klarna.models.payment_dispute_updated import (
    PaymentDisputeUpdated,
)
from klarna.utilities.union_type_lookup import (
    UnionTypeLookUp,
)

CallbacksEventType = Union[
    PaymentDisputeStateChange,
    PaymentDisputeUpdated,
    UnknownEvent,
]

class CallbacksHandler:
    """
     Handles the Callbacks Events
    """

    @staticmethod
    def parse_event(request: Request) -> CallbacksEventType:
        """
         Parse the event.

        :return: PaymentDisputeStateChange, PaymentDisputeUpdated for successful
                 parsing; UnknownEvent for unknown events.
        :rtype: Union[PaymentDisputeStateChange, PaymentDisputeUpdated, UnknownEvent]
        """
        # Deserialize payload
        try:
            union = UnionTypeLookUp.get("Callbacks")
            return APIHelper.deserialize_union_type(union, request.raw_body)
        except Exception as e:
            return UnknownEvent([
                "Deserialization failed.",
                str(e),
            ])
