"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.exceptions.api_exception import (
    ApiException,
)


class CancelOrderRequestStatusNoRequestFoundException(ApiException):
    def __init__(self, reason, response):
        """Initialize CancelOrderRequestStatusNoRequestFoundException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(CancelOrderRequestStatusNoRequestFoundException,
              self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        self.reason_code =\
            dictionary.get("reason_code")\
            if dictionary.get("reason_code")\
                else None
        self.reason_message =\
            dictionary.get("reason_message")\
            if dictionary.get("reason_message")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _reason_code=self.reason_code
        _reason_message=self.reason_message
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"status={_status!s}, "
            f"reason_code={_reason_code!s}, "
            f"reason_message={_reason_message!s}, "
            f")"
        )
