"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.exceptions.api_exception import (
    ApiException,
)


class NoSuchOrderErrorMessageException(ApiException):
    def __init__(self, reason, response):
        """Initialize NoSuchOrderErrorMessageException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(NoSuchOrderErrorMessageException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.correlation_id =\
            dictionary.get("correlation_id")\
            if dictionary.get("correlation_id")\
                else None
        self.error_code =\
            dictionary.get("error_code")\
            if dictionary.get("error_code")\
                else None
        self.error_messages =\
            dictionary.get("error_messages")\
            if dictionary.get("error_messages")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _correlation_id=(
            self.correlation_id
            if hasattr(self, "correlation_id")
            else None
        )
        _error_code=(
            self.error_code
            if hasattr(self, "error_code")
            else None
        )
        _error_messages=(
            self.error_messages
            if hasattr(self, "error_messages")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"correlation_id={_correlation_id!s}, "
            f"error_code={_error_code!s}, "
            f"error_messages={_error_messages!s}, "
            f")"
        )
