"""klarna.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from klarna.api_helper import APIHelper
from klarna.exceptions.api_exception import (
    ApiException,
)


class TechnicalErrorInternalErrorErrorException(ApiException):
    def __init__(self, reason, response):
        """Initialize TechnicalErrorInternalErrorErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(TechnicalErrorInternalErrorErrorException,
              self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error_id =\
            dictionary.get("error_id")\
            if dictionary.get("error_id")\
                else None
        self.error_code =\
            dictionary.get("error_code")\
            if dictionary.get("error_code")\
                else None
        self.error_message =\
            dictionary.get("error_message")\
            if dictionary.get("error_message")\
                else None
        self.doc_url =\
            dictionary.get("doc_url")\
            if dictionary.get("doc_url")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _error_id=self.error_id
        _error_code=self.error_code
        _error_type=self.error_type
        _error_message=self.error_message
        _doc_url=(
            self.doc_url
            if hasattr(self, "doc_url")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"error_id={_error_id!s}, "
            f"error_code={_error_code!s}, "
            f"error_type={_error_type!s}, "
            f"error_message={_error_message!s}, "
            f"doc_url={_doc_url!s}, "
            f")"
        )
